# **ETL HOMICIDIOS_LESIONES_ANALYSIS**

## 1. Importación de Librerías

In [1]:
import pandas as pd # Cargamos la libreria de "pandas" para la manipulación y el análisis de datos
import numpy as np # Cargamos la librería de "numpy" para realizar cálculos lógicos y matemáticos sobre cuadros y matrices en el caso que lo necesitemos
import datetime
import warnings
warnings.filterwarnings("ignore")

## 2. ETL (Extract - Transform - Load)

### 2.1. Carga de DataSet

In [2]:
#Colocamos la ruta de los archivos EXCEL
ruta_homicidios = r'Dataset/homicidios.xlsx'
ruta_lesiones = r'Dataset/lesiones.xlsx'


In [3]:
#Leemos el archivo EXCEL
df_homicidios_hechos = pd.read_excel(ruta_homicidios, sheet_name='HECHOS')
df_homicidios_victimas = pd.read_excel(ruta_homicidios, sheet_name='VICTIMAS')
df_lesiones_hechos = pd.read_excel(ruta_lesiones, sheet_name='HECHOS')
df_lesiones_victimas = pd.read_excel(ruta_lesiones, sheet_name='VICTIMAS')

In [4]:
#Visualizamos el DataFrame "df_homicidios_hechos"
df_homicidios_hechos.head()

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00  4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00  1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00  7   
3  2016-0004           1 2016-01-10  2016   1  10  00:00:00  0   
4  2016-0005           1 2016-01-21  2016   1  21  05:20:00  5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  Altura  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...     NaN   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...     NaN   
2                         AV ENTRE RIOS 2034       AVENIDA  ...  2034.0   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...     NaN   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...     NaN   

                                 Cruce  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   
2                                  NaN   
3             VILLEGAS, CONRADO, GRAL.   
4              SAENZ PE?A, LUIS, PRES.   

                               Dirección Normalizada COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                ENTRE RIOS AV. 2034      1   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   

                                 XY (CABA)         pos x         pos y  \
0    Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1    Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2   Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3    Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4  Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   

    PARTICIPANTES VICTIMA    ACUSADO  
0       MOTO-AUTO    MOTO       AUTO  
1  AUTO-PASAJEROS    AUTO  PASAJEROS  
2       MOTO-AUTO    MOTO       AUTO  
3         MOTO-SD    MOTO         SD  
4  MOTO-PASAJEROS    MOTO  PASAJEROS  

[5 rows x 21 columns]

In [5]:
#Visualizamos el DataFrame "df_homicidios_victimas"
df_homicidios_victimas.head()

ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO   19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO   70   
2  2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO   30   
3  2016-0004 2016-01-10  2016   1  10  CONDUCTOR    MOTO  MASCULINO   18   
4  2016-0005 2016-01-21  2016   1  21  CONDUCTOR    MOTO  MASCULINO   29   

   FECHA_FALLECIMIENTO  
0  2016-01-01 00:00:00  
1  2016-01-02 00:00:00  
2  2016-01-03 00:00:00  
3                   SD  
4  2016-02-01 00:00:00

In [6]:
#Visualizamos el DataFrame "df_lesiones_hechos"
df_lesiones_hechos.head()

id  n_victimas  aaaa  mm  dd                fecha      hora  \
0  LC-2019-0000179           1  2019   1   1  2019-01-01 00:00:00  09:00:00   
1  LC-2019-0000053           1  2019   1   1  2019-01-01 00:00:00  01:55:00   
2  LC-2019-0000063           1  2019   1   1  2019-01-01 00:00:00  02:00:00   
3  LC-2019-0000079           1  2019   1   1  2019-01-01 00:00:00  02:30:00   
4  LC-2019-0000082           4  2019   1   1  2019-01-01 00:00:00  04:30:00   

  franja_hora direccion_normalizada comuna  ...     latutid   victima acusado  \
0           9                    SD     14  ...  -34.559658  CICLISTA      SD   
1           1                    SD      8  ...  -34.669125      AUTO      SD   
2           2                    SD      8  ...  -34.677556        SD      SD   
3           2                    SD      7  ...  -34.647349    PEATON      SD   
4           4                    SD      3  ...  -34.604579      AUTO      SD   

   participantes moto auto transporte_publico camion ciclista gravedad  
0    CICLISTA-SD   SD   SD                 SD     SD        x       SD  
1        AUTO-SD   SD    x                 SD     SD       SD       SD  
2          SD-SD   SD   SD                 SD     SD       SD       SD  
3      PEATON-SD    x   SD                 SD     SD       SD       SD  
4        AUTO-SD   SD   SD                  x     SD       SD       SD  

[5 rows x 27 columns]

In [7]:
#Visualizamos el DataFrame "df_lesiones_victimas"
df_lesiones_victimas.head()

ID hecho   AAA  MM  DD     FECHA  VEHICULO_VICTIMA   SEXO  \
0  LC-2019-0000053  2019   1   1 2019-01-01               sd  Varon   
1  LC-2019-0000063  2019   1   1 2019-01-01               sd     SD   
2  LC-2019-0000079  2019   1   1 2019-01-01               sd  Varon   
3  LC-2019-0000082  2019   1   1 2019-01-01               sd  Varon   
4  LC-2019-0000082  2019   1   1 2019-01-01               sd  Mujer   

  EDAD_VICTIMA GRAVEDAD  
0           57       SD  
1           SD       SD  
2           SD       SD  
3           45       SD  
4           45       SD

### 2.2. Analisís Descriptivo del DataSet

#### 2.2.1. Definición de las Funciones Descriptivas de los Dataset


In [8]:
#Definimos algunas funciones para que nos facilita la descripcion de las principales caracteristicas del DataFrame
def caracteristicas_df(df):
    """
    Describe de forma general la base de datos .

    Esta función simplemente muestra el tamaño, información general y
    la cantidad de datos nulos.

    Parametros
    ----------
    df (pandas.DataFrame): El DataFrame que se va a analizar.

    Returns:
    ----------
        - 'df.shape': Numero de filas y columnas
        - 'df.info': Muestra información general del DataFrame

    """
    print('*'*10 + '|'*10 + 'FORMA DE BASE DE DATOS' + '|'*10 + '*'*10, end = '\n'*2)
    print(f'Tiene {df.shape[0]} filas y {df.shape[1]} columnas o variables')
    print(end = '\n'*2)

    print('*'*10 + '|'*10 + 'INFORMACION GENERAL DE LA BASE DE DATOS' + '|'*10 + '*'*10, end = '\n'*2)
    print(df.info(), end = '\n'*2)

def valores_nulos_df(df):
    """
    Revisa presencia de valores nulos en un DataFrame.
    Esta función toma un DataFrame como entrada y devuelve un resumen que incluye información sobre
    el porcentaje de valores no nulos y nulos, así como la ncantidad de valores nulos por columna.

    Parametros:
    ----------
    df (pandas.DataFrame): El DataFrame que se va a analizar.

    Returns:
    ----------
        pandas.DataFrame: Un DataFrame que contiene el resumen de cada columna, incluyendo:
        - 'nombre': Nombre de cada columna.
        - 'no_nulos_%': Porcentaje de valores no nulos en cada columna.
        - 'nulos_%': Porcentaje de valores nulos en cada columna.
        - 'nulos': Cantidad de valores nulos en cada columna.

    """
    mi_df = {"nombre": [], "tipo_datos": [], "nulos_%": [], "nulos": []}

    for columna in df.columns:
        porcentaje_no_nulos = (df[columna].count() / len(df)) * 100
        mi_df["nombre"].append(columna)
        mi_df["tipo_datos"].append(df[columna].apply(type).unique())
        mi_df["nulos_%"].append(round(100-porcentaje_no_nulos, 2))
        mi_df["nulos"].append(df[columna].isnull().sum())

    df_nulos = pd.DataFrame(mi_df)

    return df_nulos

#### 2.2.2. Descripcion de los Dataset

##### *df_homicidios_hechos*

In [9]:
#Visualizamos las caracteristicas de df_homicidios_hechos
caracteristicas_df(df_homicidios_hechos)

**********||||||||||FORMA DE BASE DE DATOS||||||||||**********

Tiene 696 filas y 21 columnas o variables


**********||||||||||INFORMACION GENERAL DE LA BASE DE DATOS||||||||||**********

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object       

In [10]:
#Visualizamos los valores nulos de df_homicidios_hechos
valores_nulos_df(df_homicidios_hechos)

nombre                                         tipo_datos  \
0                      ID                                    [<class 'str'>]   
1              N_VICTIMAS                                    [<class 'int'>]   
2                   FECHA  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                    AAAA                                    [<class 'int'>]   
4                      MM                                    [<class 'int'>]   
5                      DD                                    [<class 'int'>]   
6                    HORA  [<class 'datetime.time'>, <class 'str'>, <clas...   
7                      HH                     [<class 'int'>, <class 'str'>]   
8         LUGAR_DEL_HECHO                                    [<class 'str'>]   
9           TIPO_DE_CALLE                                    [<class 'str'>]   
10                  Calle                   [<class 'str'>, <class 'float'>]   
11                 Altura                                  [<class 'float'>]   
12                  Cruce                   [<class 'str'>, <class 'float'>]   
13  Dirección Normalizada                   [<class 'str'>, <class 'float'>]   
14                 COMUNA                                    [<class 'int'>]   
15              XY (CABA)                                    [<class 'str'>]   
16                  pos x                                    [<class 'str'>]   
17                  pos y                                    [<class 'str'>]   
18          PARTICIPANTES                                    [<class 'str'>]   
19                VICTIMA                                    [<class 'str'>]   
20                ACUSADO                                    [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.00      0  
8      0.00      0  
9      0.00      0  
10     0.14      1  
11    81.47    567  
12    24.57    171  
13     1.15      8  
14     0.00      0  
15     0.00      0  
16     0.00      0  
17     0.00      0  
18     0.00      0  
19     0.00      0  
20     0.00      0

Este conjunto contiene 21 columnas y 696 filas. Las columnas que contiene son:

*   **ID:** Identificador unico del siniestro.
*   **N_VICTIMAS:** Cantidad de victimas.
*   **FECHA:** Fecha en formato "dd/mm/aa".
*   **AAAA:** Año.
*   **MM:** Mes.
*   **DD:** Día del mes.
*   **HORA:** Hora del siniestro.
*   **HH:** Franja horaria entera.
*   **LUGAR_DE_HECHO:** Dirección del hecho.
*   **TIPO_DE_CALLE:** Tipo de arteria.En el caso de intersecciones a nivel se clasifica según la de mayor jerarquia.
*   **Calle:** Nombre de la arteria donde se produjo el hecho.
*   **Altura:** Altura de la arteria donde se produjo el hecho.
*   **Cruce:** Cruce en caso de que sea una encrucijada.
*   **Dirección Normalizada:** Dirección en formato normalizado USIG.
*   **COMUNA:** Comuna de la ciudad (1 al 15).
*   **XY(CABA):** Geocodificacion plana.
*   **pos X:** Longitud con separador punto WGS84.
*   **pos Y:** Latitud con separador punto WGS84.
*   **PARTICIPANTES:** Conjuncion de victima y acusado.
*   **VICTIMA:** Vehiculo que ocupaba quien haya fallecido o se haya lastimado a raiz del hecho, o bien peaton.Clasificación agragada del tipo de vehiculos.
*   **ACUSADO:** Vehiculo que ocupaba quien resulto acusado del hecho, sin implicar culpabilidad legal.

##### *df_homicidios_victimas*

In [11]:
#Visualizamos las caracteristicas de df_homicidios_victimas
caracteristicas_df(df_homicidios_victimas)

**********||||||||||FORMA DE BASE DE DATOS||||||||||**********

Tiene 717 filas y 10 columnas o variables


**********||||||||||INFORMACION GENERAL DE LA BASE DE DATOS||||||||||**********

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_hecho             717 non-null    object        
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64         
 3   MM                   717 non-null    int64         
 4   DD                   717 non-null    int64         
 5   ROL                  717 non-null    object        
 6   VICTIMA              717 non-null    object        
 7   SEXO                 717 non-null    object        
 8   EDAD                 717 non-null    object        
 9   FECHA_FALLECIMIENTO  717 non-null    object        
dtypes: datetime64[ns]

In [12]:
#Visualizamos los valores nulos de df_homicidios_victimas
valores_nulos_df(df_homicidios_victimas)

nombre                                         tipo_datos  \
0             ID_hecho                                    [<class 'str'>]   
1                FECHA  [<class 'pandas._libs.tslibs.timestamps.Timest...   
2                 AAAA                                    [<class 'int'>]   
3                   MM                                    [<class 'int'>]   
4                   DD                                    [<class 'int'>]   
5                  ROL                                    [<class 'str'>]   
6              VICTIMA                                    [<class 'str'>]   
7                 SEXO                                    [<class 'str'>]   
8                 EDAD                     [<class 'int'>, <class 'str'>]   
9  FECHA_FALLECIMIENTO       [<class 'datetime.datetime'>, <class 'str'>]   

   nulos_%  nulos  
0      0.0      0  
1      0.0      0  
2      0.0      0  
3      0.0      0  
4      0.0      0  
5      0.0      0  
6      0.0      0  
7      0.0      0  
8      0.0      0  
9      0.0      0

Este conjunto contiene 10 columnas y 717 filas. Las columnas que contiene son:

*   **ID:** Identificador unico del siniestro.
*   **FECHA:** Fecha en formato "dd/mm/aa".
*   **AAAA:** Año.
*   **MM:** Mes.
*   **DD:** Día del mes.
*   **ROL:** Posición relativa al vehiculo que presentaba la victima en el momento del siniestro.
*   **VICTIMA:** Vehiculo que ocupaba quien haya fallecido o se haya lastimado a raiz del hecho, o bien peaton. Clasificiacion agregada del tipo de vehiculos.
*   **SEXO:** Sexo informado por fuente policial de la victima.
*   **EDAD:** Edad de la victima al momento del siniestro.
*   **FECHA_FALLECIMIENTO:** Fecha de fallecimiento de la victima.

##### *df_lesiones_hechos*

In [13]:
#Visualizamos las caracteristicas de df_lesiones_hechos
caracteristicas_df(df_lesiones_hechos)

**********||||||||||FORMA DE BASE DE DATOS||||||||||**********

Tiene 23785 filas y 27 columnas o variables


**********||||||||||INFORMACION GENERAL DE LA BASE DE DATOS||||||||||**********

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23785 entries, 0 to 23784
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     23785 non-null  object 
 1   n_victimas             23785 non-null  int64  
 2   aaaa                   23785 non-null  int64  
 3   mm                     23785 non-null  int64  
 4   dd                     23785 non-null  int64  
 5   fecha                  23785 non-null  object 
 6   hora                   23785 non-null  object 
 7   franja_hora            23780 non-null  object 
 8   direccion_normalizada  23732 non-null  object 
 9   comuna                 23616 non-null  object 
 10  tipo_calle             23785 non-null  object 
 11  otra_direccion     

In [14]:
#Visualizamos los valores nulos de df_lesiones_hechos
valores_nulos_df(df_lesiones_hechos)

nombre                                       tipo_datos  \
0                      id                                  [<class 'str'>]   
1              n_victimas                                  [<class 'int'>]   
2                    aaaa                                  [<class 'int'>]   
3                      mm                                  [<class 'int'>]   
4                      dd                                  [<class 'int'>]   
5                   fecha     [<class 'datetime.datetime'>, <class 'str'>]   
6                    hora         [<class 'datetime.time'>, <class 'str'>]   
7             franja_hora  [<class 'int'>, <class 'str'>, <class 'float'>]   
8   direccion_normalizada                 [<class 'str'>, <class 'float'>]   
9                  comuna  [<class 'int'>, <class 'str'>, <class 'float'>]   
10             tipo_calle                                  [<class 'str'>]   
11         otra_direccion                                  [<class 'str'>]   
12                  calle                 [<class 'float'>, <class 'str'>]   
13                 altura                                [<class 'float'>]   
14                  cruce                 [<class 'float'>, <class 'str'>]   
15   geocodificacion_CABA                 [<class 'str'>, <class 'float'>]   
16               longitud  [<class 'str'>, <class 'float'>, <class 'int'>]   
17                latutid  [<class 'str'>, <class 'float'>, <class 'int'>]   
18                victima                                  [<class 'str'>]   
19                acusado                                  [<class 'str'>]   
20          participantes                                  [<class 'str'>]   
21                   moto  [<class 'str'>, <class 'int'>, <class 'float'>]   
22                   auto  [<class 'str'>, <class 'int'>, <class 'float'>]   
23     transporte_publico  [<class 'str'>, <class 'int'>, <class 'float'>]   
24                 camion  [<class 'str'>, <class 'int'>, <class 'float'>]   
25               ciclista  [<class 'str'>, <class 'float'>, <class 'int'>]   
26               gravedad                                  [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.02      5  
8      0.22     53  
9      0.71    169  
10     0.00      0  
11     0.00      0  
12    45.90  10918  
13    46.31  11014  
14    60.45  14378  
15     0.16     39  
16     1.10    262  
17     1.10    262  
18     0.00      0  
19     0.00      0  
20     0.00      0  
21     0.39     93  
22     0.39     93  
23     0.39     93  
24     0.39     93  
25     0.39     93  
26     0.00      0

Este conjunto contiene 27 columnas y 23785 filas. Las columnas que contiene son:

*   **siniestro_vial:** Incidente ocurrido en una via de acceso publico en el que participa al menos un vehiculo y que resulta .
*   **id:** Identificador unico del siniestro.
*   **n_victimas:** Cantidad de victimas.
*   **aaaa:** Año.
*   **mm:** Mes.
*   **dd:** Día del mes.
*   **fecha:** Fecha en formato "dd/mm/aa".
*   **hora:** Hora del siniestro.
*   **franja_hora:** Franja horaria entera.
*   **direccion_normalizada:** Dirección en formato normalizado USIG.
*   **comuna:** Comuna de CABA con jurisdiccion segun la ubicacion.
*   **tipo_calle:** Tipo de arteria.En el caso de intersecciones a nivel se clasifica según la de mayor jerarquia.
*   **otra_direccion:** Dirección en formato alternativo.
*   **calle:** Nombre de la arteria donde se produjo el hecho.
*   **altura:** Altura de la arteria donde se produjo el hecho.
*   **cruce:** Cruce en caso de que sea una encrucijada.
*   **geocodificacion_CABA:** Geocodificacion plana.
*   **longitud:** Longitud con separador punto WGS84.
*   **latitud:** Latitud con separador punto WGS84.
*   **victima:** Vehiculo que ocupaba quien haya fallecido o se haya lastimado a raiz del hecho, o bien peaton.
*   **acusado:** Vehiculo que ocupaba quien resulto acusado del hecho, sin implicar culpabilidad legal.
*   **participantes:** Conjuncion de victima y acusado.
*   **moto:** Participacion de algun motovehiculo, sea victima o acusado.
*   **auto:** Participacion de algun automovil, sea victima o acusado.
*   **transporte_publico:** Participacion de algun vehiculo de transporte publico de pasajeros, sea victima o acusado.
*   **camion:** Participacion de algun vehiculo de cargas camion, sea victima o acusado.
*   **ciclista:** Participacion de algun ciclista, sea victima o acusado .
*   **gravedad:** Nivel maximo conocido de gravedad de la lesion de la(s) victima(s) del siniestro en funcion del tiempo de hospitalizacion.

##### *df_lesiones_victimas*

In [15]:
#Visualizamos las caracteristicas de df_lesiones_victimas
caracteristicas_df(df_lesiones_victimas)

**********||||||||||FORMA DE BASE DE DATOS||||||||||**********

Tiene 27605 filas y 9 columnas o variables


**********||||||||||INFORMACION GENERAL DE LA BASE DE DATOS||||||||||**********

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27605 entries, 0 to 27604
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   ID hecho          27605 non-null  object        
 1   AAA               27605 non-null  int64         
 2   MM                27605 non-null  int64         
 3   DD                27605 non-null  int64         
 4   FECHA             27605 non-null  datetime64[ns]
 5   VEHICULO_VICTIMA  27605 non-null  object        
 6   SEXO              27605 non-null  object        
 7   EDAD_VICTIMA      27605 non-null  object        
 8   GRAVEDAD          27605 non-null  object        
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 1.9+ MB
None



In [16]:
#Visualizamos los valores nulos de df_lesiones_victimas
valores_nulos_df(df_lesiones_victimas)

nombre                                         tipo_datos  \
0          ID hecho                                    [<class 'str'>]   
1               AAA                                    [<class 'int'>]   
2                MM                                    [<class 'int'>]   
3                DD                                    [<class 'int'>]   
4            FECHA   [<class 'pandas._libs.tslibs.timestamps.Timest...   
5  VEHICULO_VICTIMA                                    [<class 'str'>]   
6              SEXO                                    [<class 'str'>]   
7      EDAD_VICTIMA                     [<class 'int'>, <class 'str'>]   
8          GRAVEDAD                                    [<class 'str'>]   

   nulos_%  nulos  
0      0.0      0  
1      0.0      0  
2      0.0      0  
3      0.0      0  
4      0.0      0  
5      0.0      0  
6      0.0      0  
7      0.0      0  
8      0.0      0

Este conjunto contiene 9 columnas y 27605 filas. Las columnas que contiene son:

*   **ID_hecho:** Identificador unico del siniestro.
*   **AÑO:** Año.
*   **MES:** Mes.
*   **DIA:** Día del mes.
*   **FECHA:** Fecha en formato "dd/mm/aa".
*   **VEHICULO_VICTIMA:** Vehiculo que ocupaba quien haya fallecido o se haya lastimado a raiz del hecho, o bien peaton.
*   **SEXO:** Sexo informado por fuente policial de la victima.
*   **EDAD_VICTIMA:** Edad en años enteros de la victima en registro policial.
*   **GRAVEDAD:** Nivel maximo conocido de gravedad de la lesion de la victima del siniestro en funcion del tiempo de hospitalizacion.

### 2.3. Transformación de Datos

#### 2.3.1. Funciones de Transformación

In [17]:
def rango_etario(edad):
    """
    Asigna un rango etario basado en la edad proporcionada.

    Parameters:
    -----------
        - edad (int): Edad de la persona.

    Returns:
    -----------
        - str or np.nan: Etiqueta del rango etario o NaN si no corresponde a ninguno.
    """
    # Definimos los rangos etarios y sus respectivas etiquetas
    rangos_etarios = {
        (0, 2): "BEBE",
        (3, 12): "NIÑO",
        (13, 17): "ADOLESCENTE",
        (18, 29): "ADULTO JOVEN",
        (30, 39): "ADULTO MEDIANA EDAD",
        (40, 49): "ADULTO MADURO",
        (50, 59): "ADULTO MAYOR",
        (60, float('inf')): "TERCERA EDAD"
    }

    # Iteramos sobre los rangos etarios
    for rango, etiqueta in rangos_etarios.items():
        # Verificamos si la edad se encuentra en el rango actual
        if rango[0] <= edad <= rango[1]:
            return etiqueta

    # Si la edad no coincide con ningún rango, retornamos NaN
    return np.nan

def estado_gravedad(victima):
    """
    Genera una carátula basada en el tipo de victima.

    Parameters:
    -----------
        - gravedad (str): Nivel de gravedad ('LEVE', 'GRAVE' o 'FATAL').

    Returns:
    -----------
        - str: Carátula correspondiente.
    """
    # Paso 1: Verificar el nivel de gravedad y generar la carátula correspondiente
    if victima in ['CICLISTA', 'PEATON', 'MOTO', 'MONOPATIN', 'UTILITARIO']:
        return 'LESIONES GRAVES'
    elif victima in ['TAXI', 'AUTO', 'MOVIL', 'MIXTO', 'CAMIONETA']:
        return 'LESIONES MODERADAS'
    elif victima in ['TRANSPORTE PUBLICO', 'SD', 'OTRO', 'CAMION']:
        return 'LESIONES LEVES'
    else:
        # Paso 2: Manejo de casos no contemplados (otros niveles de gravedad)
        return 'NO DEFINIDO'

def sentencia(gravedad):
    """
    Genera una sentencia basada en el nivel de gravedad.

    Parameters:
    -----------
        - gravedad (str): Nivel de gravedad ('LESIONES LEVES', 'LESIONES MODERADAS' o 'LESIONES GRAVES').

    Returns:
    -----------
        - str: Carátula correspondiente.

    Steps:
    -----------
        1. Se verifica el nivel de gravedad proporcionado.
        2. Si el nivel de gravedad es 'LESIONES LEVES', se genera la carátula 'FALTA'.
        3. Si el nivel de gravedad es 'LESIONES MODERADAS', se genera la carátula 'DELITO LEVE'.
        4. Si el nivel de gravedad es 'LESIONES GRAVES', se genera la carátula 'DELITO GRAVE'.
        5. En caso de niveles de gravedad no contemplados, se devuelve 'NO DEFINIDO'.
    """
    # Paso 1: Verificamos el nivel de gravedad y generar la carátula correspondiente
    if gravedad == 'LESIONES LEVES':
        return 'FALTA'
    elif gravedad == 'LESIONES MODERADAS':
        return 'DELITO LEVE'
    elif gravedad == 'LESIONES GRAVES':
        return 'DELITO GRAVE'
    else:
        # Paso 2: Manejamos de casos no contemplados (otros niveles de gravedad)
        return 'NO DEFINIDO'
    
def verifica_duplicados(df, columna):
    '''
    Verifica y muestra filas duplicadas en un DataFrame basado en una columna específica.

    Esta función toma como entrada un DataFrame y el nombre de una columna específica.
    Luego, identifica las filas duplicadas basadas en el contenido de la columna especificada,
    las filtra y las ordena para una comparación más sencilla.

    Parameters:
    ----------
        df (pandas.DataFrame): El DataFrame en el que se buscarán filas duplicadas.
        columna (str): El nombre de la columna basada en la cual se verificarán las duplicaciones.

    Returns:
    ----------
        pandas.DataFrame or str: Un DataFrame que contiene las filas duplicadas filtradas y ordenadas,
        listas para su inspección y comparación, o el mensaje "No hay duplicados" si no se encuentran duplicados.
    '''
    # Se filtran las filas duplicadas
    duplicated_rows = df[df.duplicated(subset=columna, keep=False)]
    if duplicated_rows.empty:
        return "No hay duplicados"

    # se ordenan las filas duplicadas para comparar entre sí
    duplicated_rows_sorted = duplicated_rows.sort_values(by=columna)
    return duplicated_rows_sorted

from datetime import datetime

def convertir_a_time(x):
    '''
    Convierte un valor a un objeto de tiempo (time) de Python si es posible.

    Parameters:
    -----------
        x (str, datetime, or any): El valor que se desea convertir a un objeto de tiempo (time).

    Returns:
    -----------
        datetime.time or None: Un objeto de tiempo (time) de Python si la conversión es exitosa,
        o None si no es posible realizar la conversión.

    Raises:
    -----------
        ValueError: Si la conversión a tiempo falla debido a un formato incorrecto.

    Steps:
    -----------
        1. Se verifica si el valor es una cadena (str).
        2. Se intenta convertir la cadena a un objeto de tiempo (time) utilizando `datetime.strptime`.
        3. Si la conversión es exitosa, se devuelve el objeto de tiempo.
        4. Si la conversión no es posible debido a un `ValueError`, se maneja devolviendo `None`.
        5. Se verifica si el valor es un objeto `datetime`.
        6. Si es un objeto `datetime`, se obtiene la parte de tiempo del objeto.
        7. Si ninguna de las conversiones es posible, devuelve el valor original.
    '''
    if isinstance(x, str):
        try:
            return datetime.strptime(x, "%H:%M:%S").time()
        except ValueError:
            return None
    elif isinstance(x, datetime):
        return x.time()
    
    return x

def imputa_valor_frecuente(df, columna):
    '''
    Imputa los valores faltantes en una columna de un DataFrame con el valor más frecuente.

    Esta función reemplaza los valores "SD" con NaN en la columna especificada,
    luego calcula el valor más frecuente en esa columna y utiliza ese valor
    para imputar los valores faltantes (NaN).

    Parameters:
    -----------
        df (pandas.DataFrame): El DataFrame que contiene la columna a ser imputada.
        columna (str): El nombre de la columna en la que se realizará la imputación.

    Returns:
    -----------
        None

    Raises:
    -----------
        ValueError: Si la columna especificada no existe en el DataFrame.

    Steps:
    -----------
        1. Se reemplaza "SD" con NaN en la columna.
        2. Se calcula el valor más frecuente en la columna.
        3. Se imputan los valores NaN con el valor más frecuente.
    '''
    # Verificar si la columna especificada existe en el DataFrame
    if columna not in df.columns:
        raise ValueError(f'La columna "{columna}" no existe en el DataFrame.')

    # Reemplazar "SD" con NaN en la columna
    df[columna] = df[columna].replace(['SD', 'sd'], pd.NA)

    # Calcular el valor más frecuente en la columna
    valor_mas_frecuente = df[columna].mode().iloc[0]
    print(f'El valor más frecuente en la columna "{columna}" es: {valor_mas_frecuente}')

    # Imputar los valores NaN con el valor más frecuente
    df[columna].fillna(valor_mas_frecuente, inplace=True)

def imputa_edad_media_segun_sexo(df):
    '''
    Imputa valores faltantes en la columna 'Edad' utilizando la edad promedio según el género.

    Esta función reemplaza los valores "SD" con NaN en la columna 'Edad', calcula la edad promedio
    para cada grupo de género (Femenino y Masculino), imprime los promedios calculados y
    luego llena los valores faltantes en la columna 'Edad' utilizando el promedio correspondiente
    al género al que pertenece cada fila en el DataFrame.

    Parameters:
    -----------
        df (pandas.DataFrame): El DataFrame que contiene la columna 'Edad' a ser imputada.

    Returns:
    -----------
        None

    Raises:
    -----------
        ValueError: Si la columna 'Edad' no existe en el DataFrame.

    Steps:
    -----------
        1. Se reemplaza "SD" con NaN en la columna 'Edad'.
        2. Se calcula el promedio de edad para cada grupo de género.
        3. Se imprime la edad promedio calculada para Femenino y Masculino.
        4. Se llenan los valores NaN en la columna 'Edad' utilizando el promedio correspondiente al género.
        
    '''
    # Verificar si la columna 'Edad' existe en el DataFrame
    if 'Edad' not in df.columns:
        raise ValueError('La columna "Edad" no existe en el DataFrame.')

    # Reemplazar "SD" o "sd" con NaN en la columna 'Edad'
    df['Edad'] = df['Edad'].replace(['SD', 'sd'], pd.NA)

    # Calcular el promedio de edad para cada grupo de género
    promedio_por_genero = df.groupby('Sexo')['Edad'].mean()
    print(f'La edad promedio de Femenino es {round(promedio_por_genero["FEMENINO"])} y de Masculino es {round(promedio_por_genero["MASCULINO"])}')

    # Llenar los valores NaN en la columna 'Edad' utilizando el promedio correspondiente al género
    df['Edad'] = df.apply(lambda row: promedio_por_genero[row['Sexo']] if pd.isna(row['Edad']) else row['Edad'], axis=1)

    # Convertir la columna 'Edad' a tipo entero
    df['Edad'] = df['Edad'].astype(int)

def transformar_direccion(texto):
    """
    Reordena y normaliza las columnas referentes a las direcciones.

    Esta función toma un texto como entrada y realiza las siguientes transformaciones:
    - Convierte el texto a mayúsculas.
    - Reordena el texto en el formato deseado, eliminando la coma y normalizando abreviaciones.
    - Reemplaza abreviaciones específicas con sus formas completas.

    Parameters:
    -----------
        texto (str): El texto de la columna a transformar.

    Returns:
    -----------
        str or np.nan: El texto transformado o NaN si el input no es una cadena.

    Steps:
    -----------
        1. El texto de la columna se convierte a mayúsculas para asegurar coherencia en el formato.
        2. Si el texto contiene una coma, se divide en partes y se reordena según el formato deseado. Por ejemplo, "Calle A, Ciudad" se convierte en "Ciudad Calle A".
        3. Se reemplazan abreviaciones específicas, como 'GRAL.' por 'GENERAL', 'TTE.' por 'TENIENTE', y 'CNEL.' por 'CORONEL'.
        4. Si el texto contiene 'DR.', se divide en partes y se reordena. Lo mismo se aplica para 'AV.'.
        5. Se eliminan espacios en blanco adicionales alrededor del texto.
        6. Si el input no es una cadena, se retorna NaN.       
    
    """
    if isinstance(texto, str):
        # Convertir a mayúsculas
        texto = texto.upper()

        # Reordenar el texto
        if "," in texto:
            partes = [parte.strip() for parte in texto.split(",")]
            if len(partes) == 2:
                texto = f"{partes[1]} {partes[0]} "
            elif len(partes) == 3:
                texto = f"{partes[2]} {partes[1]} {partes[0]} "

        # Tratar abreviaciones específicas
        texto = texto.replace('GRAL.', 'GENERAL').replace('TTE.', 'TENIENTE').replace('CNEL.', 'CORONEL')

        # Tratar 'DR.' y 'AV.'
        if "DR." in texto:
            partes_dr = [parte.strip() for parte in texto.split("DR.")]
            if len(partes_dr) == 2:
                texto = f"DR. {partes_dr[0]} {partes_dr[1]}"
        
        if "AV." in texto:
            partes_av = [parte.strip() for parte in texto.split("AV.")]
            if len(partes_av) == 2:
                texto = f"AV. {partes_av[0]} {partes_av[1]}"

        # Eliminar espacios en blanco
        texto = texto.strip()

        return texto
    else:
        # Manejar casos no cadena
        return float(np.nan)

def reemplazar_participacion(value):
    '''
    Reemplaza valores en las columnas designadas para los participantes del siniestro.

    Esta función busca reemplazar valores NaN en las columnas designadas para los participantes
    del siniestro, como ['MOTO', 'AUTO', 'TRANSPORTE_PUBLICO', 'CAMION', 'CICLISTA'].

    Parameters:
    -----------
        value (str): El valor actual en la columna a ser reemplazado.

    Returns:
    -----------
        float or str: El valor reemplazado. Si el valor es 'x', se reemplaza por 1.0 (float redondeado). 
                     Si el valor es '0', se reemplaza por 0.0 (float redondeado). En otros casos, 
                     se devuelve el valor original.
    '''
    if value == 'x':
        # Si el valor es 'x', se reemplaza por 1 (float redondeado)
        return 1
    elif value == '0':
        # Si el valor es '0', se reemplaza por 0 (float redondeado)
        return 0
    else:
        # Si el valor no es 'x' ni '0', se devuelve 0
        return 0

#### 2.3.2. Transformación y eliminación de datos

##### *df_homicidios_hechos*

In [18]:
#Visualizaremos las columnas de nuestro DataFrame "df_homicidios_hechos"
df_homicidios_hechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

In [19]:
# Se coloca la primera letra en mayúscula y se reemplazan guiones por espacios
df_homicidios_hechos.columns = [x.capitalize() for x in df_homicidios_hechos.columns]

# Se renombran algunas columnas
df_homicidios_hechos = df_homicidios_hechos.rename(columns={'N_victimas':'Cantidad_Víctimas',
                                                      'Aaaa':'Anio',
                                                      'Mm':'Mes',
                                                      'Dd':'Día',
                                                      'Hh':'Parte_Horaria',
                                                      'Lugar_del_hecho': 'Lugar_del_Hecho',
                                                      'Tipo_de_calle':'Tipo_de_Calle',
                                                      'Dirección normalizada':'Dirección_Normalizada',
                                                      'Pos x':'Pos X',
                                                      'Pos y':'Pos Y',
                                                      'Xy (caba)':'XY (CABA)',
                                                      'Victima': 'Víctima'})
#Visualizamos los nombres nuevos de nuestras columnas 
df_homicidios_hechos.columns

Index(['Id', 'Cantidad_Víctimas', 'Fecha', 'Anio', 'Mes', 'Día', 'Hora',
       'Parte_Horaria', 'Lugar_del_Hecho', 'Tipo_de_Calle', 'Calle', 'Altura',
       'Cruce', 'Dirección_Normalizada', 'Comuna', 'XY (CABA)', 'Pos X',
       'Pos Y', 'Participantes', 'Víctima', 'Acusado'],
      dtype='object')

In [20]:
"""
En el analisis descriptivo que realizamos al principio se pudo observar lo siguiente:
1. La columna "Altura" tiene un porcentaje de 81.47 % nulos.
2. La columna "Cruce" tiene un porcentaje de 24.57% nulos.
3. La columna "Dirección_Normalizada" tiene un porcentaje de 1.15% nulos.
4. La columna "Victima" tiene un porcentaje de 1.29% nulos.
5. La columna "Acusado" tiene un porcentaje 3.30% nulos.

Se procedera a eliminar la columna "Altura" ya que representa si el accidente se produjo en una intersección de una arteria siendo este un número. Adicional a eso
se observa que el dato se encuentra en la columna "Lugar_del_Hecho" y "Dirección_Normalizada".

"""

#Verificamos la hipotesis dicha
df_homicidios_hechos[['Altura', 'Lugar_del_Hecho', 'Dirección_Normalizada']][2:10]


Altura                            Lugar_del_Hecho  \
2  2034.0                         AV ENTRE RIOS 2034   
3     NaN      AV LARRAZABAL Y GRAL VILLEGAS CONRADO   
4     NaN  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA    
5     NaN             AV 27 DE FEBRERO Y AV ESCALADA   
6     NaN               NOGOYA Y JOAQUIN V. GONZALES   
7     NaN        AV GENERAL PAZ Y AV DE LOS CORRALES   
8     NaN         AV BELGRANO Y BERNARDO DE IRIGOYEN   
9  1366.0                         AV ENTRE RIOS 1366   

                       Dirección_Normalizada  
2                        ENTRE RIOS AV. 2034  
3  LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.  
4    SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.  
5           27 DE FEBRERO AV. y ESCALADA AV.  
6              NOGOYA y GONZALEZ, JOAQUIN V.  
7       PAZ, GRAL. AV. y DE LOS CORRALES AV.  
8       BELGRANO AV. e IRIGOYEN, BERNARDO DE  
9                        ENTRE RIOS AV. 1366

In [21]:
#Se procede a eliminar la columna "Altura"
df_homicidios_hechos.drop('Altura', axis=1, inplace=True)

#Verificamos si efectivamente se elimino
df_homicidios_hechos.columns

Index(['Id', 'Cantidad_Víctimas', 'Fecha', 'Anio', 'Mes', 'Día', 'Hora',
       'Parte_Horaria', 'Lugar_del_Hecho', 'Tipo_de_Calle', 'Calle', 'Cruce',
       'Dirección_Normalizada', 'Comuna', 'XY (CABA)', 'Pos X', 'Pos Y',
       'Participantes', 'Víctima', 'Acusado'],
      dtype='object')

In [22]:
"""
Ahora vamos hacer un pequeño analisis de las columnas "Cruce" con las de "Lugar del Hecho" y "Tipo de Calle" debido a que estás
pueden tener datos en comun y estan estrechamente relacionadas.
"""
# Mostrar los valores nulos en relación con 'Lugar del hecho' y 'Tipo de calle' en 'Cruce'
df_homicidios_hechos[df_homicidios_hechos['Cruce'].isnull()][['Cruce', 'Lugar_del_Hecho', 'Tipo_de_Calle']][15:20]

Cruce                       Lugar_del_Hecho Tipo_de_Calle
93    NaN                     AV EVA PERON 4233       AVENIDA
100   NaN  AUTOPISTA 9 DE JULIO SUR Y AV BRASIL     AUTOPISTA
101   NaN                           MIRAVE 3500         CALLE
106   NaN      AU BUENOS AIRES - LA PLATA KM. 4     AUTOPISTA
113   NaN                   AV. ALTE. BROWN 984       AVENIDA

In [23]:
# Mostrar los valores  no nulos en relación con 'Lugar del hecho' y 'Tipo de calle' en 'Cruce'
df_homicidios_hechos[df_homicidios_hechos['Cruce'].notnull()][['Cruce', 'Lugar_del_Hecho', 'Tipo_de_Calle']][15:20]

Cruce             Lugar_del_Hecho Tipo_de_Calle
18            VEDIA            HOLMBERG Y VEDIA         CALLE
19    DIAZ, AVELINO  CURAPALIGUE Y AVELINO DIAZ       AVENIDA
20   9 DE JULIO AV.    VIAMONTE Y AV 9 DE JULIO       AVENIDA
21           DEHEZA         AV CABILDO Y DEHEZA       AVENIDA
22  ROCA, CNEL. AV.  AV GRAL PAZ Y AV CNEL ROCA      GRAL PAZ

In [24]:
# Reemplazar valores no nulos por "SI" y valores nulos por "NO" en la columna 'Cruce'
df_homicidios_hechos['Cruce'] = np.where(df_homicidios_hechos['Cruce'].notnull(), 'SI', 'NO')

#Verificamos si se aplico el cambio
df_homicidios_hechos[['Cruce', 'Lugar_del_Hecho', 'Tipo_de_Calle']]

Cruce                            Lugar_del_Hecho Tipo_de_Calle
0      SI  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA
1      SI          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ
2      NO                         AV ENTRE RIOS 2034       AVENIDA
3      SI      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA
4      SI  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA
..    ...                                        ...           ...
691    SI                          AV. RIESTRA Y MOM       AVENIDA
692    SI                    AU DELLEPIANE Y LACARRA     AUTOPISTA
693    SI                        AV. GAONA Y TERRADA       AVENIDA
694    NO                         AV. EVA PERON 4071       AVENIDA
695    NO                    PADRE CARLOS MUJICA 709         CALLE

[696 rows x 3 columns]

In [25]:
# Mostrar los valores nulos en relación con 'Lugar del hecho' y 'Tipo de calle' en 'Cruce'
df_homicidios_hechos[df_homicidios_hechos['Dirección_Normalizada'].isnull()][['Dirección_Normalizada', 'Lugar_del_Hecho', 'Tipo_de_Calle']][:15]

Dirección_Normalizada                          Lugar_del_Hecho  \
38                    NaN               AUTOPISTA LUGONES PK 10000   
106                   NaN         AU BUENOS AIRES - LA PLATA KM. 4   
119                   NaN                                       SD   
180                   NaN  AU PERITO MORENO Y RAMAL ENLACE AU1/AU6   
181                   NaN                       AU DELLEPIANE 2400   
313                   NaN                 AUTOPISTA LUGONES KM 4.7   
546                   NaN             LUGONES, LEOPOLDO AV. KM 6,1   
621                   NaN         AU BUENOS AIRES LA PLATA  KM 4,5   

    Tipo_de_Calle  
38      AUTOPISTA  
106     AUTOPISTA  
119         CALLE  
180     AUTOPISTA  
181     AUTOPISTA  
313     AUTOPISTA  
546     AUTOPISTA  
621     AUTOPISTA

In [26]:
# Mostrar los valores  no nulos en relación con 'Lugar del hecho' y 'Tipo de calle' en 'Cruce'
df_homicidios_hechos[df_homicidios_hechos['Dirección_Normalizada'].notnull()][['Dirección_Normalizada', 'Lugar_del_Hecho', 'Tipo_de_Calle']][:15]

Dirección_Normalizada  \
0   PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1                PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                 ENTRE RIOS AV. 2034   
3           LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4             SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   
5                    27 DE FEBRERO AV. y ESCALADA AV.   
6                       NOGOYA y GONZALEZ, JOAQUIN V.   
7                PAZ, GRAL. AV. y DE LOS CORRALES AV.   
8                BELGRANO AV. e IRIGOYEN, BERNARDO DE   
9                                 ENTRE RIOS AV. 1366   
10                  SCALABRINI ORTIZ, RAUL AV. y VERA   
11  REGIMIENTO DE PATRICIOS AV. y QUINQUELA MARTIN...   
12                 ACOSTA, MARIANO y JANER, ANA MARIA   
13  DE LA TORRE, LISANDRO y GARCIA GRANDE DE ZEQUE...   
14                                       SUIPACHA 156   

                                      Lugar_del_Hecho Tipo_de_Calle  
0           AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  
1                   AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  
2                                  AV ENTRE RIOS 2034       AVENIDA  
3               AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  
4           AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  
5                      AV 27 DE FEBRERO Y AV ESCALADA       AVENIDA  
6                        NOGOYA Y JOAQUIN V. GONZALES         CALLE  
7                 AV GENERAL PAZ Y AV DE LOS CORRALES      GRAL PAZ  
8                  AV BELGRANO Y BERNARDO DE IRIGOYEN       AVENIDA  
9                                  AV ENTRE RIOS 1366       AVENIDA  
10                         AV SCALABRINI ORTIZ Y VERA       AVENIDA  
11  AV REGIMIENTO DE PATRICIOS Y QUINQUELA MARTIN ...       AVENIDA  
12                   MARIANO ACOSTA Y ANA MARIA JANER       AVENIDA  
13  LISANDRO DE LA TORRE Y SEVERO GARCIA GRANDE DE...         CALLE  
14                                       SUIPACHA 156         CALLE

In [27]:
#Procederemos a normalizar las direcciones
df_homicidios_hechos['Calle']=df_homicidios_hechos['Calle'].apply(transformar_direccion)
df_homicidios_hechos['Cruce']=df_homicidios_hechos['Cruce'].apply(transformar_direccion)

In [28]:
# Procederemos a reemplazar la dirección por nuestras columnas ya normalizadas
df_homicidios_hechos['Dirección_Normalizada'] = df_homicidios_hechos.apply(
    lambda columna: (
        columna["Calle"] + " Y " + columna["Cruce"]
    ) if (
        isinstance(columna["Cruce"], str) and isinstance(columna["Calle"], str)
    ) else (
        columna["Calle"] if isinstance(columna["Calle"], str)
        else (
            columna["Cruce"] if isinstance(columna["Cruce"], str)
            else columna["Lugar_del_Hecho"]
        )
    ),
    axis=1
)

In [29]:
# Se rellenan los valores nulos con "SD" que significa "Sin Dato"
df_homicidios_hechos['Dirección_Normalizada'].fillna("SD", inplace=True)

# Verificamos si se han imputado de manera correcta
df_homicidios_hechos[df_homicidios_hechos['Dirección_Normalizada'] == 'SD'][['Dirección_Normalizada', 'Lugar_del_Hecho', 'Tipo_de_Calle']]

Empty DataFrame
Columns: [Dirección_Normalizada, Lugar_del_Hecho, Tipo_de_Calle]
Index: []

In [30]:
# Reemplazamos el valor 'GRAL PAZ' por 'AVENIDA' en la columna 'TIPO_DE_CALLE'
df_homicidios_hechos['Tipo_de_Calle'].replace('GRAL PAZ', 'AVENIDA', inplace=True)

#Verificamos si se aplico el cambio en la posicion 1 ya que antes era "GRAL PAZ"
df_homicidios_hechos['Tipo_de_Calle'][1]

'AVENIDA'

In [31]:
#Vamos a verificar si existen valores duplicados en el DataFrame 
verifica_duplicados(df_homicidios_hechos,'Id')

'No hay duplicados'

In [32]:
#Verificamos el tipo de datos de las columnas que ahora tenemos
valores_nulos_df(df_homicidios_hechos)

nombre                                         tipo_datos  \
0                      Id                                    [<class 'str'>]   
1       Cantidad_Víctimas                                    [<class 'int'>]   
2                   Fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                    Anio                                    [<class 'int'>]   
4                     Mes                                    [<class 'int'>]   
5                     Día                                    [<class 'int'>]   
6                    Hora  [<class 'datetime.time'>, <class 'str'>, <clas...   
7           Parte_Horaria                     [<class 'int'>, <class 'str'>]   
8         Lugar_del_Hecho                                    [<class 'str'>]   
9           Tipo_de_Calle                                    [<class 'str'>]   
10                  Calle                   [<class 'str'>, <class 'float'>]   
11                  Cruce                                    [<class 'str'>]   
12  Dirección_Normalizada                                    [<class 'str'>]   
13                 Comuna                                    [<class 'int'>]   
14              XY (CABA)                                    [<class 'str'>]   
15                  Pos X                                    [<class 'str'>]   
16                  Pos Y                                    [<class 'str'>]   
17          Participantes                                    [<class 'str'>]   
18                Víctima                                    [<class 'str'>]   
19                Acusado                                    [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.00      0  
8      0.00      0  
9      0.00      0  
10     0.14      1  
11     0.00      0  
12     0.00      0  
13     0.00      0  
14     0.00      0  
15     0.00      0  
16     0.00      0  
17     0.00      0  
18     0.00      0  
19     0.00      0

In [33]:
#Cantidad de valores por tipo de dato en la columna 'Hora'
df_homicidios_hechos['Hora'].apply(type).value_counts()

Hora
<class 'datetime.time'>        608
<class 'str'>                   85
<class 'datetime.datetime'>      3
Name: count, dtype: int64

In [34]:
# Cambiamos el tipo de dato de la columna 'Hora' utilizando la función convertir_a_time
df_homicidios_hechos['Hora'] = df_homicidios_hechos['Hora'].apply(lambda x: convertir_a_time(x))

# Verificamos la cantidad de valores por tipo de dato en la columna 'Hora'
print(df_homicidios_hechos['Hora'].apply(type).value_counts())

# Mostramos los registros con valores nulos (NoneType) en la columna 'Hora'
registros_nulos = df_homicidios_hechos[df_homicidios_hechos['Hora'].isna()]


Hora
<class 'datetime.time'>    695
<class 'NoneType'>           1
Name: count, dtype: int64


In [35]:
#Verificamos ese valor tipo "float" del DataFrame, notamos que es un valor NaN
df_homicidios_hechos[df_homicidios_hechos['Hora'].isnull()]

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día  Hora  \
518  2019-0103                  1 2019-12-18  2019   12   18  None   

    Parte_Horaria          Lugar_del_Hecho Tipo_de_Calle            Calle  \
518            SD  PAZ, GRAL. AV. Y GRIVEO       AVENIDA  AV. GENERAL PAZ   

    Cruce Dirección_Normalizada  Comuna  \
518    SI  AV. GENERAL PAZ Y SI      11   

                                  XY (CABA)         Pos X         Pos Y  \
518  Point (94643.11254058 103831.57115061)  -58.52169422  -34.59471640   

    Participantes Víctima Acusado  
518     MOTO-MOTO    MOTO    MOTO

In [36]:
# Calculamos la hora más común
hora_moda = df_homicidios_hechos['Hora'].mode().iloc[0]
print(f'La hora más común es: {hora_moda}')

# Reemplazamos los valores nulos por la hora más común
df_homicidios_hechos['Hora'].fillna(hora_moda, inplace=True)

La hora más común es: 09:00:00


In [37]:
# Verificamos y mostramos la distribución de tipos de datos después del reemplazo
df_homicidios_hechos['Hora'].apply(type).value_counts()

Hora
<class 'datetime.time'>    696
Name: count, dtype: int64

In [38]:
#Verificamos los valores nulos
valores_nulos_df(df_homicidios_hechos)

nombre                                         tipo_datos  \
0                      Id                                    [<class 'str'>]   
1       Cantidad_Víctimas                                    [<class 'int'>]   
2                   Fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                    Anio                                    [<class 'int'>]   
4                     Mes                                    [<class 'int'>]   
5                     Día                                    [<class 'int'>]   
6                    Hora                          [<class 'datetime.time'>]   
7           Parte_Horaria                     [<class 'int'>, <class 'str'>]   
8         Lugar_del_Hecho                                    [<class 'str'>]   
9           Tipo_de_Calle                                    [<class 'str'>]   
10                  Calle                   [<class 'str'>, <class 'float'>]   
11                  Cruce                                    [<class 'str'>]   
12  Dirección_Normalizada                                    [<class 'str'>]   
13                 Comuna                                    [<class 'int'>]   
14              XY (CABA)                                    [<class 'str'>]   
15                  Pos X                                    [<class 'str'>]   
16                  Pos Y                                    [<class 'str'>]   
17          Participantes                                    [<class 'str'>]   
18                Víctima                                    [<class 'str'>]   
19                Acusado                                    [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.00      0  
8      0.00      0  
9      0.00      0  
10     0.14      1  
11     0.00      0  
12     0.00      0  
13     0.00      0  
14     0.00      0  
15     0.00      0  
16     0.00      0  
17     0.00      0  
18     0.00      0  
19     0.00      0

In [39]:
# Se verifica el tipo de dato "Parte_Horaria"
df_homicidios_hechos['Parte_Horaria'].apply(type).value_counts()

Parte_Horaria
<class 'int'>    695
<class 'str'>      1
Name: count, dtype: int64

In [40]:
df_homicidios_hechos[df_homicidios_hechos['Parte_Horaria'].isnull()]

Empty DataFrame
Columns: [Id, Cantidad_Víctimas, Fecha, Anio, Mes, Día, Hora, Parte_Horaria, Lugar_del_Hecho, Tipo_de_Calle, Calle, Cruce, Dirección_Normalizada, Comuna, XY (CABA), Pos X, Pos Y, Participantes, Víctima, Acusado]
Index: []

In [41]:
# Imputamos el valor 9.0 en la fila con índice 518 en la columna 'Parte_Horaria'
df_homicidios_hechos.loc[518, 'Parte_Horaria'] = 9.0

In [42]:
# Mostramos registros con tipo de dato float en la columna 'Calle'
df_homicidios_hechos[df_homicidios_hechos['Calle'].apply(lambda x: isinstance(x, float))]

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día      Hora  \
119  2016-0151                  1 2016-11-18  2016   11   18  20:35:00   

    Parte_Horaria Lugar_del_Hecho Tipo_de_Calle Calle Cruce  \
119            20              SD         CALLE   NaN    NO   

    Dirección_Normalizada  Comuna    XY (CABA) Pos X Pos Y Participantes  \
119                    NO       0  Point (. .)     .     .     PEATON-SD   

    Víctima Acusado  
119  PEATON      SD

In [43]:
# Se imputa SD al dato faltante
df_homicidios_hechos['Calle'].fillna('SD', inplace=True)

In [44]:
# Mostramos registros con tipo de dato float en la columna 'Calle'
df_homicidios_hechos[df_homicidios_hechos['Lugar_del_Hecho'].apply(lambda x: isinstance(x, float))]

Empty DataFrame
Columns: [Id, Cantidad_Víctimas, Fecha, Anio, Mes, Día, Hora, Parte_Horaria, Lugar_del_Hecho, Tipo_de_Calle, Calle, Cruce, Dirección_Normalizada, Comuna, XY (CABA), Pos X, Pos Y, Participantes, Víctima, Acusado]
Index: []

In [45]:
# Imputamos 'SD' en el dato faltante de la columna 'Calle'
df_homicidios_hechos['Calle'].fillna('SD', inplace=True)

# Verificar el registro completado
df_homicidios_hechos[df_homicidios_hechos['Calle'] == 'SD']

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día      Hora  \
119  2016-0151                  1 2016-11-18  2016   11   18  20:35:00   

    Parte_Horaria Lugar_del_Hecho Tipo_de_Calle Calle Cruce  \
119            20              SD         CALLE    SD    NO   

    Dirección_Normalizada  Comuna    XY (CABA) Pos X Pos Y Participantes  \
119                    NO       0  Point (. .)     .     .     PEATON-SD   

    Víctima Acusado  
119  PEATON      SD

In [46]:
# Imputamos 'SD' en el dato faltante de la columna 'Lugar_del_Hecho'
df_homicidios_hechos['Lugar_del_Hecho'].fillna('SD', inplace=True)

# Verificamos el registro completado
df_homicidios_hechos[df_homicidios_hechos['Lugar_del_Hecho'] == 'SD']

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día      Hora  \
119  2016-0151                  1 2016-11-18  2016   11   18  20:35:00   

    Parte_Horaria Lugar_del_Hecho Tipo_de_Calle Calle Cruce  \
119            20              SD         CALLE    SD    NO   

    Dirección_Normalizada  Comuna    XY (CABA) Pos X Pos Y Participantes  \
119                    NO       0  Point (. .)     .     .     PEATON-SD   

    Víctima Acusado  
119  PEATON      SD

In [47]:
#Verificamos los valores nulos
valores_nulos_df(df_homicidios_hechos)

nombre                                         tipo_datos  \
0                      Id                                    [<class 'str'>]   
1       Cantidad_Víctimas                                    [<class 'int'>]   
2                   Fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                    Anio                                    [<class 'int'>]   
4                     Mes                                    [<class 'int'>]   
5                     Día                                    [<class 'int'>]   
6                    Hora                          [<class 'datetime.time'>]   
7           Parte_Horaria                   [<class 'int'>, <class 'float'>]   
8         Lugar_del_Hecho                                    [<class 'str'>]   
9           Tipo_de_Calle                                    [<class 'str'>]   
10                  Calle                                    [<class 'str'>]   
11                  Cruce                                    [<class 'str'>]   
12  Dirección_Normalizada                                    [<class 'str'>]   
13                 Comuna                                    [<class 'int'>]   
14              XY (CABA)                                    [<class 'str'>]   
15                  Pos X                                    [<class 'str'>]   
16                  Pos Y                                    [<class 'str'>]   
17          Participantes                                    [<class 'str'>]   
18                Víctima                                    [<class 'str'>]   
19                Acusado                                    [<class 'str'>]   

    nulos_%  nulos  
0       0.0      0  
1       0.0      0  
2       0.0      0  
3       0.0      0  
4       0.0      0  
5       0.0      0  
6       0.0      0  
7       0.0      0  
8       0.0      0  
9       0.0      0  
10      0.0      0  
11      0.0      0  
12      0.0      0  
13      0.0      0  
14      0.0      0  
15      0.0      0  
16      0.0      0  
17      0.0      0  
18      0.0      0  
19      0.0      0

In [48]:
df_homicidios_hechos['Víctima'].unique()

array(['MOTO', 'AUTO', 'PEATON', 'SD', 'CARGAS', 'BICICLETA', 'PASAJEROS',
       'MOVIL', 'OBJETO FIJO', 'PEATON_MOTO'], dtype=object)

In [49]:
df_homicidios_hechos['Acusado'].unique()

array(['AUTO', 'PASAJEROS', 'SD', 'OBJETO FIJO', 'CARGAS', 'MOTO',
       'MULTIPLE', 'OTRO', 'BICICLETA', 'TREN'], dtype=object)

In [50]:
"""
Se observa que los datos en "Víctima" podemos encontrar OBJETO_FIJO y PEATON_MOTO que son datos raros y vamos a cambiarlo por OTRO 
"""
#Filtramos los datos que tienen esos valores
df_homicidios_hechos[df_homicidios_hechos['Víctima'].isin(['OBJETO FIJO', 'PEATON_MOTO'])]

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día      Hora  \
230  2017-0108                  2 2017-09-02  2017    9    2  04:53:08   
583  2020-0063                  2 2020-12-05  2020   12    5  07:10:00   

    Parte_Horaria           Lugar_del_Hecho Tipo_de_Calle            Calle  \
230             4   AV. GRAL. PAZ Y MACHAIN       AVENIDA  AV. GENERAL PAZ   
583             7  NUEVA YORK Y ALTA GRACIA         CALLE       NUEVA YORK   

    Cruce Dirección_Normalizada  Comuna  \
230    SI  AV. GENERAL PAZ Y SI      12   
583    SI       NUEVA YORK Y SI      11   

                                  XY (CABA)         Pos X         Pos Y  \
230  Point (97098.48468623 109019.96106626)  -58.49491054  -34.54795581   
583  Point (94080.62190808 102083.62453795)  -58.52783814  -34.61047001   

        Participantes      Víctima Acusado  
230  AUTO-OBJETO FIJO  OBJETO FIJO    AUTO  
583  PEATON_MOTO-MOTO  PEATON_MOTO    MOTO

In [51]:
# Reemplazar 'OBJETO FIJO' y 'PEATON_MOTO' por 'OTRO' en la columna 'Víctima'
df_homicidios_hechos['Víctima'] = df_homicidios_hechos['Víctima'].replace({'OBJETO FIJO': 'OTRO', 'PEATON_MOTO': 'OTRO'})

# Verificar los cambios
df_homicidios_hechos['Víctima'].unique()

array(['MOTO', 'AUTO', 'PEATON', 'SD', 'CARGAS', 'BICICLETA', 'PASAJEROS',
       'MOVIL', 'OTRO'], dtype=object)

In [52]:
#Verificamos los tipos de datos y valores nulos
valores_nulos_df(df_homicidios_hechos)

nombre                                         tipo_datos  \
0                      Id                                    [<class 'str'>]   
1       Cantidad_Víctimas                                    [<class 'int'>]   
2                   Fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                    Anio                                    [<class 'int'>]   
4                     Mes                                    [<class 'int'>]   
5                     Día                                    [<class 'int'>]   
6                    Hora                          [<class 'datetime.time'>]   
7           Parte_Horaria                   [<class 'int'>, <class 'float'>]   
8         Lugar_del_Hecho                                    [<class 'str'>]   
9           Tipo_de_Calle                                    [<class 'str'>]   
10                  Calle                                    [<class 'str'>]   
11                  Cruce                                    [<class 'str'>]   
12  Dirección_Normalizada                                    [<class 'str'>]   
13                 Comuna                                    [<class 'int'>]   
14              XY (CABA)                                    [<class 'str'>]   
15                  Pos X                                    [<class 'str'>]   
16                  Pos Y                                    [<class 'str'>]   
17          Participantes                                    [<class 'str'>]   
18                Víctima                                    [<class 'str'>]   
19                Acusado                                    [<class 'str'>]   

    nulos_%  nulos  
0       0.0      0  
1       0.0      0  
2       0.0      0  
3       0.0      0  
4       0.0      0  
5       0.0      0  
6       0.0      0  
7       0.0      0  
8       0.0      0  
9       0.0      0  
10      0.0      0  
11      0.0      0  
12      0.0      0  
13      0.0      0  
14      0.0      0  
15      0.0      0  
16      0.0      0  
17      0.0      0  
18      0.0      0  
19      0.0      0

In [53]:
#Se observan algunos datos faltantes en la columna XY(CABA)
df_homicidios_hechos[df_homicidios_hechos['XY (CABA)'] =='Point (. .)'].head()

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día      Hora  \
35   2016-0049                  1 2016-04-17  2016    4   17  00:00:00   
38   2016-0052                  1 2016-04-20  2016    4   20  20:00:00   
71   2016-0096                  1 2016-07-25  2016    7   25  07:00:00   
106  2016-0136                  1 2016-10-25  2016   10   25  00:00:00   
119  2016-0151                  1 2016-11-18  2016   11   18  20:35:00   

    Parte_Horaria                                    Lugar_del_Hecho  \
35              0  AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI KM....   
38             20                         AUTOPISTA LUGONES PK 10000   
71              7       AUTOPISTA DELLEPIANE LUIS TTE. GRAL. KM. 2,3   
106             0                   AU BUENOS AIRES - LA PLATA KM. 4   
119            20                                                 SD   

    Tipo_de_Calle                                       Calle Cruce  \
35      AUTOPISTA  AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI    NO   
38      AUTOPISTA                        AV. LEOPOLDO LUGONES    NO   
71      AUTOPISTA  AUTOPISTA DELLEPIANE LUIS TENIENTE GENERAL    NO   
106     AUTOPISTA           AUTOPISTA BUENOS AIRES - LA PLATA    NO   
119         CALLE                                          SD    NO   

                               Dirección_Normalizada  Comuna    XY (CABA)  \
35   AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI Y NO       4  Point (. .)   
38                         AV. LEOPOLDO LUGONES Y NO      13  Point (. .)   
71   AUTOPISTA DELLEPIANE LUIS TENIENTE GENERAL Y NO       8  Point (. .)   
106           AUTOPISTA BUENOS AIRES - LA PLATA Y NO       4  Point (. .)   
119                                               NO       0  Point (. .)   

                  Pos X               Pos Y Participantes Víctima Acusado  
35   -58.37714647568196  -34.63657525428238         SD-SD      SD      SD  
38                    .                   .       MOTO-SD    MOTO      SD  
71   -58.47433193007387  -34.66684950051973   MOTO-CARGAS    MOTO  CARGAS  
106                   .                   .   MOTO-CARGAS    MOTO  CARGAS  
119                   .                   .     PEATON-SD  PEATON      SD

In [54]:
# Reemplazar los valores faltantes por 0 en las columnas 'Pos x', 'Pos y' y 'XY (CABA)'
df_homicidios_hechos['Pos X'] = df_homicidios_hechos['Pos X'].replace('.', 0)
df_homicidios_hechos['Pos Y'] = df_homicidios_hechos['Pos Y'].replace('.', 0)
df_homicidios_hechos['XY (CABA)'] = df_homicidios_hechos['XY (CABA)'].replace('Point (. .)', 0)

In [55]:
# Verificar los cambios para algunas filas específicas
filas_verificacion = [320, 119, 200]
registros_cambiados = df_homicidios_hechos.loc[filas_verificacion, ['Pos X', 'Pos Y', 'XY (CABA)']]
registros_cambiados

Pos X         Pos Y                                XY (CABA)
320  -58.52927982  -34.63931752    Point (93950.50587297 98883.37644525)
119             0             0                                        0
200  -58.40781467  -34.60425669  Point (105089.38820014 102773.44772064)

In [56]:
# Agregamos una nueva columna 'GRAVEDAD' con el valor constante "FATAL" para diferenciar df_homicidios_hechos de lesiones
df_homicidios_hechos["Gravedad"] = "FATAL"

In [57]:
# Creamos la columna CARATULA POLICIAL y la rellenamos con HOMICIDIO CULPOSO
df_homicidios_hechos['Sentencia'] = 'HOMICIDIO CULPOSO'

In [58]:
#Visualizamos el DataFrame final
df_homicidios_hechos.head()

Id  Cantidad_Víctimas      Fecha  Anio  Mes  Día      Hora  \
0  2016-0001                  1 2016-01-01  2016    1    1  04:00:00   
1  2016-0002                  1 2016-01-02  2016    1    2  01:15:00   
2  2016-0003                  1 2016-01-03  2016    1    3  07:00:00   
3  2016-0004                  1 2016-01-10  2016    1   10  00:00:00   
4  2016-0005                  1 2016-01-21  2016    1   21  05:20:00   

  Parte_Horaria                            Lugar_del_Hecho Tipo_de_Calle  ...  \
0             4  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...   
1             1          AV GRAL PAZ  Y AV DE LOS CORRALES       AVENIDA  ...   
2             7                         AV ENTRE RIOS 2034       AVENIDA  ...   
3             0      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...   
4             5  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...   

   Dirección_Normalizada Comuna                                XY (CABA)  \
0  AV. PIEDRA BUENA Y SI      8    Point (98896.78238426 93532.43437792)   
1   AV. GENERAL PAZ Y SI      9    Point (95832.05571093 95505.41641999)   
2    AV. ENTRE RIOS Y NO      1   Point (106684.29090040 99706.57687843)   
3    AV. LARRAZABAL Y SI      8    Point (99840.65224780 94269.16534422)   
4      AV. SAN JUAN Y SI      1  Point (106980.32827929 100752.16915795)   

          Pos X         Pos Y   Participantes Víctima    Acusado Gravedad  \
0  -58.47533969  -34.68757022       MOTO-AUTO    MOTO       AUTO    FATAL   
1  -58.50877521  -34.66977709  AUTO-PASAJEROS    AUTO  PASAJEROS    FATAL   
2  -58.39040293  -34.63189362       MOTO-AUTO    MOTO       AUTO    FATAL   
3  -58.46503904  -34.68092974         MOTO-SD    MOTO         SD    FATAL   
4  -58.38718297  -34.62246630  MOTO-PASAJEROS    MOTO  PASAJEROS    FATAL   

           Sentencia  
0  HOMICIDIO CULPOSO  
1  HOMICIDIO CULPOSO  
2  HOMICIDIO CULPOSO  
3  HOMICIDIO CULPOSO  
4  HOMICIDIO CULPOSO  

[5 rows x 22 columns]

##### *df_homicidios_victimas*

In [59]:
#Visualizaremos las columnas de nuestro DataFrame "df_homicidios_victimas"
df_homicidios_victimas.columns

Index(['ID_hecho', 'FECHA', 'AAAA', 'MM', 'DD', 'ROL', 'VICTIMA', 'SEXO',
       'EDAD', 'FECHA_FALLECIMIENTO'],
      dtype='object')

In [60]:
# Se coloca la primera letra en mayúscula y se reemplazan guiones por espacios
df_homicidios_victimas.columns = [x.capitalize() for x in df_homicidios_victimas.columns]

# Se renombran algunas columnas
df_homicidios_victimas = df_homicidios_victimas.rename(columns={'Id_hecho':'Id',
                                                      'Aaaa':'Anio',
                                                      'Mm':'Mes',
                                                      'Dd':'Día',
                                                      'Fecha_fallecimiento':'Fecha_Fallecimiento',})
#Visualizamos los nombres nuevos de nuestras columnas 
df_homicidios_victimas.columns

Index(['Id', 'Fecha', 'Anio', 'Mes', 'Día', 'Rol', 'Victima', 'Sexo', 'Edad',
       'Fecha_Fallecimiento'],
      dtype='object')

In [61]:
#Verificamos si existen datos duplicados en el DataFrame
df_homicidios_victimas[df_homicidios_victimas.duplicated()]

Empty DataFrame
Columns: [Id, Fecha, Anio, Mes, Día, Rol, Victima, Sexo, Edad, Fecha_Fallecimiento]
Index: []

In [62]:
#También pasamos a verificar si existen Ids duplicados
verifica_duplicados(df_homicidios_victimas,'Id')

Id      Fecha  Anio  Mes  Día                   Rol Victima  \
29   2016-0041 2016-03-29  2016    3   29             CONDUCTOR    MOTO   
30   2016-0041 2016-03-29  2016    3   29  PASAJERO_ACOMPAÑANTE    MOTO   
98   2016-0126 2016-09-18  2016    9   18             CONDUCTOR    AUTO   
99   2016-0126 2016-09-18  2016    9   18  PASAJERO_ACOMPAÑANTE    AUTO   
163  2017-0026 2017-02-26  2017    2   26  PASAJERO_ACOMPAÑANTE    AUTO   
164  2017-0026 2017-02-26  2017    2   26             CONDUCTOR    AUTO   
173  2017-0035 2017-03-23  2017    3   23             CONDUCTOR    AUTO   
174  2017-0035 2017-03-23  2017    3   23  PASAJERO_ACOMPAÑANTE    AUTO   
175  2017-0035 2017-03-23  2017    3   23  PASAJERO_ACOMPAÑANTE    AUTO   
177  2017-0036 2017-03-29  2017    3   29             CONDUCTOR    MOTO   
176  2017-0036 2017-03-29  2017    3   29  PASAJERO_ACOMPAÑANTE    MOTO   
186  2017-0050 2017-04-28  2017    4   28             CONDUCTOR    MOTO   
187  2017-0050 2017-04-28  2017    4   28  PASAJERO_ACOMPAÑANTE    MOTO   
237  2017-0108 2017-09-02  2017    9    2  PASAJERO_ACOMPAÑANTE    AUTO   
238  2017-0108 2017-09-02  2017    9    2  PASAJERO_ACOMPAÑANTE    AUTO   
242  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE    AUTO   
243  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE    AUTO   
253  2017-0126 2017-10-14  2017   10   14  PASAJERO_ACOMPAÑANTE    AUTO   
254  2017-0126 2017-10-14  2017   10   14             CONDUCTOR    AUTO   
278  2017-0153 2017-12-11  2017   12   11             CONDUCTOR    MOTO   
277  2017-0153 2017-12-11  2017   12   11  PASAJERO_ACOMPAÑANTE    MOTO   
300  2018-0015 2018-02-06  2018    2    6             CONDUCTOR    MOTO   
301  2018-0015 2018-02-06  2018    2    6  PASAJERO_ACOMPAÑANTE    MOTO   
312  2018-0026 2018-03-09  2018    3    9             CONDUCTOR   MOVIL   
313  2018-0026 2018-03-09  2018    3    9  PASAJERO_ACOMPAÑANTE   MOVIL   
325  2018-0038 2018-04-20  2018    4   20                PEATON  PEATON   
326  2018-0038 2018-04-20  2018    4   20                PEATON  PEATON   
373  2018-0085 2018-08-03  2018    8    3  PASAJERO_ACOMPAÑANTE    MOTO   
374  2018-0085 2018-08-03  2018    8    3             CONDUCTOR    MOTO   
388  2018-0098 2018-09-09  2018    9    9  PASAJERO_ACOMPAÑANTE    AUTO   
387  2018-0098 2018-09-09  2018    9    9             CONDUCTOR    AUTO   
418  2018-0128 2018-11-25  2018   11   25  PASAJERO_ACOMPAÑANTE    AUTO   
419  2018-0128 2018-11-25  2018   11   25  PASAJERO_ACOMPAÑANTE    AUTO   
444  2019-0010 2019-02-02  2019    2    2                PEATON  PEATON   
445  2019-0010 2019-02-02  2019    2    2                PEATON  PEATON   
576  2020-0038 2020-08-30  2020    8   30             CONDUCTOR    AUTO   
577  2020-0038 2020-08-30  2020    8   30             CONDUCTOR    AUTO   
602  2020-0063 2020-12-05  2020   12    5                PEATON  PEATON   
603  2020-0063 2020-12-05  2020   12    5  PASAJERO_ACOMPAÑANTE    MOTO   
616  2020-0077 2020-12-25  2020   12   25             CONDUCTOR    MOTO   
617  2020-0077 2020-12-25  2020   12   25  PASAJERO_ACOMPAÑANTE    MOTO   

          Sexo Edad  Fecha_Fallecimiento  
29   MASCULINO   54  2016-03-29 00:00:00  
30   MASCULINO   SD  2016-03-30 00:00:00  
98   MASCULINO   37                   SD  
99   MASCULINO   60                   SD  
163   FEMENINO   23  2017-02-26 00:00:00  
164  MASCULINO   19  2017-02-26 00:00:00  
173  MASCULINO   28  2017-03-23 00:00:00  
174  MASCULINO   32  2017-03-23 00:00:00  
175  MASCULINO   30  2017-03-23 00:00:00  
177  MASCULINO   20  2017-03-29 00:00:00  
176   FEMENINO   SD  2017-03-29 00:00:00  
186  MASCULINO   46  2017-04-28 00:00:00  
187  MASCULINO   16  2017-04-28 00:00:00  
237  MASCULINO   17  2017-09-02 00:00:00  
238  MASCULINO   10  2017-09-02 00:00:00  
242  MASCULINO    1                   SD  
243  MASCULINO   SD  2017-09-13 00:00:00  
253  MASCULINO   39                   SD  
254  MASCULINO   36  2017-10-14 00:00:00  
2

In [63]:
# Visualizamos la cantidad de valores por tipo de dato en la columna 'Edad'
df_homicidios_victimas['Edad'].apply(type).value_counts()


Edad
<class 'int'>    664
<class 'str'>     53
Name: count, dtype: int64

In [64]:
"""
Para imputar los valores faltantes en la columna 'Edad', se planea utilizar el promedio de las edades de las víctimas, 
considerando el género ('Sexo'). Dado que la variable 'Sexo' también presenta faltantes, se procederá a completar estos valores 
utilizando el valor más frecuente entre las víctimas. Luego, con ambas columnas actualizadas, se calculará el promedio de las edades 
por género y se utilizará este promedio para imputar los valores faltantes en la columna 'Edad', asegurando así una imputación más 
precisa y contextualizada. Este enfoque tiene como objetivo gestionar de manera integral los datos faltantes, considerando tanto la 
información de género como la de edad, para obtener resultados más significativos y representativos.

"""
# Filtramos las filas donde la columna 'Edad' contiene valores de tipo cadena (str)
df_homicidios_victimas[df_homicidios_victimas['Edad'].apply(lambda x: isinstance(x, str))]


Id      Fecha  Anio  Mes  Día                   Rol    Victima  \
30   2016-0041 2016-03-29  2016    3   29  PASAJERO_ACOMPAÑANTE       MOTO   
33   2016-0045 2016-04-11  2016    4   11             CONDUCTOR       MOTO   
35   2016-0048 2016-04-15  2016    4   15                PEATON     PEATON   
36   2016-0049 2016-04-17  2016    4   17                    SD         SD   
39   2016-0052 2016-04-20  2016    4   20                    SD       MOTO   
55   2016-0077 2016-06-13  2016    6   13                PEATON     PEATON   
63   2016-0085 2016-06-29  2016    6   29                    SD       MOTO   
72   2016-0096 2016-07-25  2016    7   25             CONDUCTOR       MOTO   
89   2016-0115 2016-09-02  2016    9    2                    SD         SD   
93   2016-0119 2016-09-04  2016    9    4  PASAJERO_ACOMPAÑANTE         SD   
108  2016-0136 2016-10-25  2016   10   25             CONDUCTOR       MOTO   
119  2016-0148 2016-11-16  2016   11   16             CONDUCTOR       MOTO   
121  2016-0151 2016-11-18  2016   11   18                PEATON     PEATON   
138  2016-0171 2016-12-25  2016   12   25             CONDUCTOR       MOTO   
141  2016-0174 2016-12-27  2016   12   27                    SD         SD   
142  2016-0175 2016-12-27  2016   12   27                PEATON     PEATON   
165  2017-0027 2017-02-26  2017    2   26                PEATON     PEATON   
176  2017-0036 2017-03-29  2017    3   29  PASAJERO_ACOMPAÑANTE       MOTO   
182  2017-0042 2017-04-10  2017    4   10             CONDUCTOR       MOTO   
225  2017-0093 2017-07-25  2017    7   25                PEATON     PEATON   
243  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE       AUTO   
275  2017-0151 2017-12-04  2017   12    4                PEATON     PEATON   
277  2017-0153 2017-12-11  2017   12   11  PASAJERO_ACOMPAÑANTE       MOTO   
299  2018-0014 2018-01-31  2018    1   31                PEATON     PEATON   
328  2018-0040 2018-04-27  2018    4   27                PEATON     PEATON   
359  2018-0071 2018-07-10  2018    7   10             CONDUCTOR       MOTO   
367  2018-0079 2018-07-23  2018    7   23                PEATON     PEATON   
371  2018-0083 2018-08-02  2018    8    2             CONDUCTOR       MOTO   
377  2018-0088 2018-08-17  2018    8   17             CONDUCTOR       MOTO   
391  2018-0101 2018-09-21  2018    9   21             CONDUCTOR       AUTO   
421  2018-0130 2018-12-03  2018   12    3             CONDUCTOR       MOTO   
444  2019-0010 2019-02-02  2019    2    2                PEATON     PEATON   
446  2019-0011 2019-02-10  2019    2   10                PEATON     PEATON   
454  2019-0019 2019-03-06  2019    3    6             CONDUCTOR       MOTO   
457  2019-0022 2019-03-15  2019    3   15  PASAJERO_ACOMPAÑANTE       AUTO   
461  2019-0026 2019-03-28  2019    3   28                PEATON     PEATON   
463  2019-0028 2019-04-06  2019    4    6                PEATON     PEATON   
469  2019-0034 2019-04-21  2019    4   21             CONDUCTOR       MOTO   
479  2019-0043 2019-05-21  2019    5   21              CICLISTA  BICICLETA   
498  2019-0063 2019-08-04  2019    8    4  PASAJERO_ACOMPAÑANTE       MOTO   
506  2019-0071 2019-08-27  2019    8   27                PEATON     PEATON   
529  2019-0094 2019-11-18  2019   11   18  PASAJERO_ACOMPAÑANTE       MOTO   
530  2019-0095 2019-11-20  2019   11   20             CONDUCTOR       MOTO   
548  2020-0010 2020-02-08  2020    2    8             CONDUCTOR       MOTO   
552  2020-0014 2020-02-27  2020    2   27             CONDUCTOR       MOTO   
555  2020-0017 2020-03-05  2020    3    5                PEATON     PEATON   
563  2020-0025 2020-05-12  2020    5   12                PEATON     PEATON   
572  2020-0034 2020-08-02  2020    8    2                PEATON     PEATON   
579  2020-0040 2020-09-12  2020    9   12             CONDUCTOR       AUTO   
631  2021-0012 2021-01-29  2021    1   29                PEATON     PEATON   
639  2021-0020 2021-02-21  2021   

In [65]:
# Imputa valor mas frecuente en la columna "Sexo"
imputa_valor_frecuente(df_homicidios_victimas, 'Sexo')

El valor más frecuente en la columna "Sexo" es: MASCULINO


In [66]:
#Imputamos el valor de la edad teniendo el "Sexo"
imputa_edad_media_segun_sexo(df_homicidios_victimas)

La edad promedio de Femenino es 51 y de Masculino es 40


In [67]:
# Contar la cantidad de "SD" en la columna "Rol"
cantidad_sd_en_rol = len(df_homicidios_victimas[df_homicidios_victimas['Rol'] == 'SD'])
print(f"La cantidad de 'SD' en la columna 'Rol' es de {cantidad_sd_en_rol}")

# Contar la cantidad de "SD" en la columna "Victima"
cantidad_sd_en_victima = len(df_homicidios_victimas[df_homicidios_victimas['Victima'] == 'SD'])
print(f"La cantidad de 'SD' en la columna 'Víctima' es de {cantidad_sd_en_victima}")

La cantidad de 'SD' en la columna 'Rol' es de 11
La cantidad de 'SD' en la columna 'Víctima' es de 9


In [68]:
# Imputamos valor mas frecuente en la columna "Rol"
imputa_valor_frecuente(df_homicidios_victimas, 'Rol')

# Imputamos valor mas frecuente en la columna victima
imputa_valor_frecuente(df_homicidios_victimas, 'Victima')

El valor más frecuente en la columna "Rol" es: CONDUCTOR
El valor más frecuente en la columna "Victima" es: MOTO


In [69]:
# Se eliminan las columnas repetidas
df_homicidios_victimas.drop(['Fecha_Fallecimiento'], axis=1, inplace=True)
df_homicidios_victimas.columns

Index(['Id', 'Fecha', 'Anio', 'Mes', 'Día', 'Rol', 'Victima', 'Sexo', 'Edad'], dtype='object')

In [70]:
# Agregamos una nueva columna 'GRAVEDAD' con el valor constante 'FATAL' para diferenciar homicidios de lesiones
df_homicidios_victimas['Gravedad'] = 'FATAL'

In [71]:
# Aplicamos la funcion para asignar el rango etario
df_homicidios_victimas['Rango_Etario'] = df_homicidios_victimas['Edad'].apply(lambda x: rango_etario(x))

In [72]:
# Intercambiamos el valor 'PASAJERO_ACOMPAÑANTE' por 'PASAJERO' para unificar
df_homicidios_victimas['Rol'] = df_homicidios_victimas['Rol'].replace('PASAJERO_ACOMPAÑANTE','PASAJERO')

In [73]:
# Aplicamos la función sentencia a la columna 'Gravedad'
df_homicidios_victimas['Sentencia'] = 'HOMOCIDIO CULPOSO'

In [74]:
#Verificamos si aún existen datos nulos
valores_nulos_df(df_homicidios_victimas)

nombre                                         tipo_datos  nulos_%  \
0             Id                                    [<class 'str'>]      0.0   
1          Fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...      0.0   
2           Anio                                    [<class 'int'>]      0.0   
3            Mes                                    [<class 'int'>]      0.0   
4            Día                                    [<class 'int'>]      0.0   
5            Rol                                    [<class 'str'>]      0.0   
6        Victima                                    [<class 'str'>]      0.0   
7           Sexo                                    [<class 'str'>]      0.0   
8           Edad                                    [<class 'int'>]      0.0   
9       Gravedad                                    [<class 'str'>]      0.0   
10  Rango_Etario                                    [<class 'str'>]      0.0   
11     Sentencia                                    [<class 'str'>]      0.0   

    nulos  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
10      0  
11      0

In [75]:
#Visualizamos la nueva DataFrame
df_homicidios_victimas.head()

Id      Fecha  Anio  Mes  Día        Rol Victima       Sexo  Edad  \
0  2016-0001 2016-01-01  2016    1    1  CONDUCTOR    MOTO  MASCULINO    19   
1  2016-0002 2016-01-02  2016    1    2  CONDUCTOR    AUTO  MASCULINO    70   
2  2016-0003 2016-01-03  2016    1    3  CONDUCTOR    MOTO  MASCULINO    30   
3  2016-0004 2016-01-10  2016    1   10  CONDUCTOR    MOTO  MASCULINO    18   
4  2016-0005 2016-01-21  2016    1   21  CONDUCTOR    MOTO  MASCULINO    29   

  Gravedad         Rango_Etario          Sentencia  
0    FATAL         ADULTO JOVEN  HOMOCIDIO CULPOSO  
1    FATAL         TERCERA EDAD  HOMOCIDIO CULPOSO  
2    FATAL  ADULTO MEDIANA EDAD  HOMOCIDIO CULPOSO  
3    FATAL         ADULTO JOVEN  HOMOCIDIO CULPOSO  
4    FATAL         ADULTO JOVEN  HOMOCIDIO CULPOSO

##### *df_lesiones_hechos*

In [76]:
df_lesiones_hechos.columns

Index(['id', 'n_victimas', 'aaaa', 'mm', 'dd', 'fecha', 'hora', 'franja_hora',
       'direccion_normalizada', 'comuna', 'tipo_calle', 'otra_direccion',
       'calle', 'altura', 'cruce', 'geocodificacion_CABA', 'longitud',
       'latutid', 'victima', 'acusado', 'participantes', 'moto', 'auto',
       'transporte_publico', 'camion', 'ciclista', 'gravedad'],
      dtype='object')

In [77]:
# Se coloca la primera letra en mayúscula y se reemplazan guiones por espacios
df_lesiones_hechos.columns = [x.capitalize() for x in df_lesiones_hechos.columns]

# Se renombran algunas columnas
df_lesiones_hechos = df_lesiones_hechos.rename(columns={'id':'Id',
                                                      'N_victimas':'Cantidad_Víctimas',
                                                      'Aaaa': 'Anio',
                                                      'Mm':'Mes',
                                                      'Dd':'Día',
                                                      'Franja_hora':'Parte_Horaria',
                                                      'Direccion_normalizada':'Dirección_Normalizada',
                                                      'Tipo_calle':'Tipo_Calle',
                                                      'Otra_direccion':'Otra_Dirección',
                                                      'Geocodificacion_caba':'XY (CABA)',
                                                      'Longitud': 'Pos X',
                                                      'Latutid' : 'Pos Y',
                                                      'Victima': 'Víctima',
                                                      'Camion': 'Camión',
                                                      'Transporte_publico':'Transporte_Público',
                                                      })
#Visualizamos los nombres nuevos de nuestras columnas 
df_lesiones_hechos.columns

Index(['Id', 'Cantidad_Víctimas', 'Anio', 'Mes', 'Día', 'Fecha', 'Hora',
       'Parte_Horaria', 'Dirección_Normalizada', 'Comuna', 'Tipo_Calle',
       'Otra_Dirección', 'Calle', 'Altura', 'Cruce', 'XY (CABA)', 'Pos X',
       'Pos Y', 'Víctima', 'Acusado', 'Participantes', 'Moto', 'Auto',
       'Transporte_Público', 'Camión', 'Ciclista', 'Gravedad'],
      dtype='object')

In [78]:
valores_nulos_df(df_lesiones_hechos)

nombre                                       tipo_datos  \
0                      Id                                  [<class 'str'>]   
1       Cantidad_Víctimas                                  [<class 'int'>]   
2                    Anio                                  [<class 'int'>]   
3                     Mes                                  [<class 'int'>]   
4                     Día                                  [<class 'int'>]   
5                   Fecha     [<class 'datetime.datetime'>, <class 'str'>]   
6                    Hora         [<class 'datetime.time'>, <class 'str'>]   
7           Parte_Horaria  [<class 'int'>, <class 'str'>, <class 'float'>]   
8   Dirección_Normalizada                 [<class 'str'>, <class 'float'>]   
9                  Comuna  [<class 'int'>, <class 'str'>, <class 'float'>]   
10             Tipo_Calle                                  [<class 'str'>]   
11         Otra_Dirección                                  [<class 'str'>]   
12                  Calle                 [<class 'float'>, <class 'str'>]   
13                 Altura                                [<class 'float'>]   
14                  Cruce                 [<class 'float'>, <class 'str'>]   
15              XY (CABA)                 [<class 'str'>, <class 'float'>]   
16                  Pos X  [<class 'str'>, <class 'float'>, <class 'int'>]   
17                  Pos Y  [<class 'str'>, <class 'float'>, <class 'int'>]   
18                Víctima                                  [<class 'str'>]   
19                Acusado                                  [<class 'str'>]   
20          Participantes                                  [<class 'str'>]   
21                   Moto  [<class 'str'>, <class 'int'>, <class 'float'>]   
22                   Auto  [<class 'str'>, <class 'int'>, <class 'float'>]   
23     Transporte_Público  [<class 'str'>, <class 'int'>, <class 'float'>]   
24                 Camión  [<class 'str'>, <class 'int'>, <class 'float'>]   
25               Ciclista  [<class 'str'>, <class 'float'>, <class 'int'>]   
26               Gravedad                                  [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.02      5  
8      0.22     53  
9      0.71    169  
10     0.00      0  
11     0.00      0  
12    45.90  10918  
13    46.31  11014  
14    60.45  14378  
15     0.16     39  
16     1.10    262  
17     1.10    262  
18     0.00      0  
19     0.00      0  
20     0.00      0  
21     0.39     93  
22     0.39     93  
23     0.39     93  
24     0.39     93  
25     0.39     93  
26     0.00      0

In [79]:
# Modificamos la composición de la columna Id para asemejarla a la de homicidios
df_lesiones_hechos['Id'] = df_lesiones_hechos['Id'].str.replace('LC-', '').str.strip()

In [80]:
#Cantidad de valores por tipo de dato en la columna 'Hora'
df_lesiones_hechos['Hora'].apply(type).value_counts()

Hora
<class 'datetime.time'>    18131
<class 'str'>               5654
Name: count, dtype: int64

In [81]:
# Cambiamos el tipo de dato de la columna 'Hora' utilizando la función convertir_a_time
df_lesiones_hechos['Hora'] = df_lesiones_hechos['Hora'].apply(lambda x: convertir_a_time(x))

# Verificamos la cantidad de valores por tipo de dato en la columna 'Hora'
print(df_lesiones_hechos['Hora'].apply(type).value_counts())

# Mostramos los registros con valores nulos (NoneType) en la columna 'Hora'
registros_nulos = df_lesiones_hechos[df_lesiones_hechos['Hora'].isna()]

Hora
<class 'datetime.time'>    18131
<class 'NoneType'>          5654
Name: count, dtype: int64


In [82]:
# Calculamos la hora más común
hora_moda = df_lesiones_hechos['Hora'].mode().iloc[0]
print(f'La hora más común es: {hora_moda}')

# Reemplazamos los valores nulos por la hora más común
df_lesiones_hechos['Hora'].fillna(hora_moda, inplace=True)

La hora más común es: 00:00:00


In [83]:
#Verificamos los valores por tipo de dato en la columna 'Hora'
df_lesiones_hechos['Hora'].apply(type).value_counts()

Hora
<class 'datetime.time'>    23785
Name: count, dtype: int64

In [84]:
#Verificamos los valores por tipo de dato en la columna 'Fecha'
df_lesiones_hechos['Fecha'].apply(type).value_counts()

Fecha
<class 'datetime.datetime'>    23784
<class 'str'>                      1
Name: count, dtype: int64

In [85]:
# Mostramos registros con tipo de dato str en la columna 'Fecha'
df_lesiones_hechos[df_lesiones_hechos['Fecha'].apply(lambda x: isinstance(x, str))]

Id  Cantidad_Víctimas  Anio  Mes  Día      Fecha      Hora  \
23784  2020-0244615                  1  2020    5   17  5/17/2020  21:00:00   

      Parte_Horaria Dirección_Normalizada Comuna  ...        Pos Y Víctima  \
23784            21                    SD     SD  ...  -3472890716    MOTO   

      Acusado  Participantes Moto Auto Transporte_Público Camión Ciclista  \
23784    AUTO      MOTO-AUTO    x    x                  0      0        0   

      Gravedad  
23784       SD  

[1 rows x 27 columns]

In [86]:
# Convertir la fila 23784 de la columna a datetime
df_lesiones_hechos.at[23784, 'Fecha'] = datetime.strptime(df_lesiones_hechos.at[23784, 'Fecha'], '%m/%d/%Y')

In [87]:
#Verificamos los valores por tipo de dato en la columna 'Fecha'
df_lesiones_hechos['Fecha'].apply(type).value_counts()

Fecha
<class 'datetime.datetime'>    23785
Name: count, dtype: int64

In [88]:
#Verificamos los valores por tipo de dato en la columna 'Parte_Horaria'
df_lesiones_hechos['Parte_Horaria'].apply(type).value_counts()

Parte_Horaria
<class 'int'>      23776
<class 'float'>        5
<class 'str'>          4
Name: count, dtype: int64

In [89]:
# Mostramos registros con tipo de dato str en la columna 'Parte_Horaria'
df_lesiones_hechos[df_lesiones_hechos['Parte_Horaria'].apply(lambda x: isinstance(x, str))]

Id  Cantidad_Víctimas  Anio  Mes  Día  \
1462   PFA-2019-0000120                  1  2019    2   26   
9039   PFA-2019-0000301                  1  2019   11    4   
9928   PNA-2019-0005246                  0  2019   12   20   
20916      2021-0448511                  1  2021    8   23   

                     Fecha      Hora Parte_Horaria  \
1462   2019-02-26 00:00:00  00:00:00            sd   
9039   2019-11-04 00:00:00  00:00:00            sd   
9928   2019-12-20 00:00:00  00:00:00            sd   
20916  2021-08-23 00:00:00  00:00:00            sd   

              Dirección_Normalizada Comuna  ... Pos Y Víctima Acusado  \
1462              SAN JUAN AV. 1941    NaN  ...   NaN      SD      SD   
9039   ANTARTIDA ARGENTINA AV. 1200    NaN  ...   NaN      SD      SD   
9928         27 DE FEBRERO AV. 6300    NaN  ...   NaN      SD      SD   
20916                            SD     SD  ...    SD      SD      SD   

       Participantes Moto Auto Transporte_Público Camión Ciclista Gravedad  
1462           SD-SD   SD   SD                 SD     SD       SD       SD  
9039           SD-SD   SD   SD                 SD     SD       SD       SD  
9928           SD-SD   SD   SD                 SD     SD       SD       SD  
20916          SD-SD   SD   SD                 SD     SD       SD       SD  

[4 rows x 27 columns]

In [90]:
# Reemplazamos 'sd' con 0 en la columna 'Parte_Horaria'
df_lesiones_hechos['Parte_Horaria'] = df_lesiones_hechos['Parte_Horaria'].replace('sd', 0)

In [91]:
# Mostramos registros con tipo de dato float en la columna 'Parte_Horaria'
df_lesiones_hechos[df_lesiones_hechos['Parte_Horaria'].apply(lambda x: isinstance(x, float))]

Id  Cantidad_Víctimas  Anio  Mes  Día                Fecha  \
0      2019-0000179                  1  2019    1    1  2019-01-01 00:00:00   
1      2019-0000053                  1  2019    1    1  2019-01-01 00:00:00   
2      2019-0000063                  1  2019    1    1  2019-01-01 00:00:00   
3      2019-0000079                  1  2019    1    1  2019-01-01 00:00:00   
4      2019-0000082                  4  2019    1    1  2019-01-01 00:00:00   
...             ...                ...   ...  ...  ...                  ...   
23780  2021-0652849                  1  2021   12   31  2021-12-31 00:00:00   
23781  2021-0652865                  2  2021   12   31  2021-12-31 00:00:00   
23782  2021-0652907                  1  2021   12   31  2021-12-31 00:00:00   
23783  2021-0652921                  1  2021   12   31  2021-12-31 00:00:00   
23784  2020-0244615                  1  2020    5   17  2020-05-17 00:00:00   

           Hora  Parte_Horaria                 Dirección_Normalizada Comuna  \
0      09:00:00            9.0                                    SD     14   
1      01:55:00            1.0                                    SD      8   
2      02:00:00            2.0                                    SD      8   
3      02:30:00            2.0                                    SD      7   
4      04:30:00            4.0                                    SD      3   
...         ...            ...                                   ...    ...   
23780  19:30:00           19.0  ALBERDI, JUAN BAUTISTA AV. y GUAMINI      9   
23781  19:40:00           19.0       ALBERDI, JUAN BAUTISTA AV. 4436      9   
23782  20:00:00           20.0                                    SD      1   
23783  22:00:00           22.0               LINIERS VIRREY y MORENO      5   
23784  21:00:00           21.0                                    SD     SD   

       ...             Pos Y   Víctima             Acusado  \
0      ...        -34.559658  CICLISTA                  SD   
1      ...        -34.669125      AUTO                  SD   
2      ...        -34.677556        SD                  SD   
3      ...        -34.647349    PEATON                  SD   
4      ...        -34.604579      AUTO                  SD   
...    ...               ...       ...                 ...   
23780  ...  -34.659713573880        SD                  SD   
23781  ...  -34.641753304864        SD                  SD   
23782  ...        -34.583083        SD                  SD   
23783  ...  -34.614288229345      MOTO  TRANSPORTE PUBLICO   
23784  ...       -3472890716      MOTO                AUTO   

                 Participantes Moto Auto Transporte_Público Camión Ciclista  \
0                  CICLISTA-SD   SD   SD                 SD     SD        x   
1                      AUTO-SD   SD    x                 SD     SD       SD   
2                        SD-SD   SD   SD                 SD     SD       SD   
3                    PEATON-SD    x   SD                 SD     SD       SD   
4                      AUTO-SD   SD   SD                  x     SD       SD   
...                        ...  ...  ...                ...    ...      ...   
23780                    SD-SD   SD   SD                 SD     SD       SD   
23781                    SD-SD   SD   SD                 SD     SD       SD   
23782                    SD-SD   SD   SD                 SD     SD       SD   
23783  MOTO-TRANSPORTE PUBLICO    x    0                  x      0        0   
23784                MOTO-AUTO    x    x                  0      0        0   

      Gravedad  
0           SD  
1           SD  
2           SD  
3           SD  
4           SD  
...        ...  
23780       SD  
23781       SD  
23782       SD  
23783    GRAVE  
23784       SD  

[23785 rows x 27 columns]

In [92]:
# Reemplazamos 'sd' con 0 en la columna 'Parte_Horaria'
df_lesiones_hechos['Parte_Horaria'] = df_lesiones_hechos['Parte_Horaria'].replace(np.nan, 0)

In [93]:
#Verificamos los valores por tipo de dato en la columna 'Parte_Horaria'
df_lesiones_hechos['Parte_Horaria'].apply(type).value_counts()

Parte_Horaria
<class 'float'>    23785
Name: count, dtype: int64

In [94]:
valores_nulos_df(df_lesiones_hechos)

nombre                                       tipo_datos  \
0                      Id                                  [<class 'str'>]   
1       Cantidad_Víctimas                                  [<class 'int'>]   
2                    Anio                                  [<class 'int'>]   
3                     Mes                                  [<class 'int'>]   
4                     Día                                  [<class 'int'>]   
5                   Fecha                    [<class 'datetime.datetime'>]   
6                    Hora                        [<class 'datetime.time'>]   
7           Parte_Horaria                                [<class 'float'>]   
8   Dirección_Normalizada                 [<class 'str'>, <class 'float'>]   
9                  Comuna  [<class 'int'>, <class 'str'>, <class 'float'>]   
10             Tipo_Calle                                  [<class 'str'>]   
11         Otra_Dirección                                  [<class 'str'>]   
12                  Calle                 [<class 'float'>, <class 'str'>]   
13                 Altura                                [<class 'float'>]   
14                  Cruce                 [<class 'float'>, <class 'str'>]   
15              XY (CABA)                 [<class 'str'>, <class 'float'>]   
16                  Pos X  [<class 'str'>, <class 'float'>, <class 'int'>]   
17                  Pos Y  [<class 'str'>, <class 'float'>, <class 'int'>]   
18                Víctima                                  [<class 'str'>]   
19                Acusado                                  [<class 'str'>]   
20          Participantes                                  [<class 'str'>]   
21                   Moto  [<class 'str'>, <class 'int'>, <class 'float'>]   
22                   Auto  [<class 'str'>, <class 'int'>, <class 'float'>]   
23     Transporte_Público  [<class 'str'>, <class 'int'>, <class 'float'>]   
24                 Camión  [<class 'str'>, <class 'int'>, <class 'float'>]   
25               Ciclista  [<class 'str'>, <class 'float'>, <class 'int'>]   
26               Gravedad                                  [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.00      0  
8      0.22     53  
9      0.71    169  
10     0.00      0  
11     0.00      0  
12    45.90  10918  
13    46.31  11014  
14    60.45  14378  
15     0.16     39  
16     1.10    262  
17     1.10    262  
18     0.00      0  
19     0.00      0  
20     0.00      0  
21     0.39     93  
22     0.39     93  
23     0.39     93  
24     0.39     93  
25     0.39     93  
26     0.00      0

In [95]:
"""
En el analisis descriptivo que realizamos al principio se pudo observar lo siguiente:
1. La columna "Franja_Hora" tiene un porcentaje de 0.02 % nulos.
2. La columna "Dirección_Normalizada" tiene un porcentaje de 0.22% nulos.
3. La columna "Comuna" tiene un porcentaje de 0.71% nulos.
4. La columna "Calle" tiene un porcentaje de 45.90% nulos.
5. La columna "Altura" tiene un porcentaje 46.31% nulos.
6. La columna "Cruce" tiene un porcentaje 60.45% nulos.
7. La columna "XY (CABA)" tiene un porcentaje 0.16% nulos.
8. La columna "Pos X" tiene un porcentaje 1.10% nulos.
9. La columna "Pos Y" tiene un porcentaje 1.10% nulos.
10. La columna "Moto" tiene un porcentaje 0.39% nulos.
11. La columna "Auto" tiene un porcentaje 0.39% nulos.
12. La columna "Transporte_Público" tiene un porcentaje 0.39% nulos.
13. La columna "Camión" tiene un porcentaje 0.39% nulos.
14. La columna "Ciclista" tiene un porcentaje 0.39% nulos.

Se procedera a eliminar la columna "Altura" ya que representa si el accidente se produjo en una intersección de una arteria siendo este un número. Adicional a eso
se observa que el dato se encuentra en la columna "Calle", "Dirección_Normalizada", "Otra_Dirección, "Cruce".

"""

#Verificamos la hipotesis dicha
df_lesiones_hechos[df_lesiones_hechos['Altura'].notnull()][['Altura','Calle', 'Otra_Dirección', 'Dirección_Normalizada','Cruce']][15:20]

Altura                       Calle Otra_Dirección  \
3459  3026.0          YRIGOYEN, HIPOLITO             SD   
3793   768.0                   NAZCA AV.             SD   
4094   255.0  ALBERDI, JUAN BAUTISTA AV.             SD   
4170   700.0              DIRECTORIO AV.             SD   
4245  1501.0    DON PEDRO DE MENDOZA AV.             SD   

               Dirección_Normalizada Cruce  
3459         YRIGOYEN, HIPOLITO 3026   NaN  
3793                   NAZCA AV. 768   NaN  
4094  ALBERDI, JUAN BAUTISTA AV. 255   NaN  
4170              DIRECTORIO AV. 700   NaN  
4245   DON PEDRO DE MENDOZA AV. 1501   NaN

In [96]:
#Se procede a eliminar la columna "Altura"
df_lesiones_hechos.drop('Altura', axis=1, inplace=True)

#Verificamos si efectivamente se elimino
df_lesiones_hechos.columns

Index(['Id', 'Cantidad_Víctimas', 'Anio', 'Mes', 'Día', 'Fecha', 'Hora',
       'Parte_Horaria', 'Dirección_Normalizada', 'Comuna', 'Tipo_Calle',
       'Otra_Dirección', 'Calle', 'Cruce', 'XY (CABA)', 'Pos X', 'Pos Y',
       'Víctima', 'Acusado', 'Participantes', 'Moto', 'Auto',
       'Transporte_Público', 'Camión', 'Ciclista', 'Gravedad'],
      dtype='object')

In [97]:
#Eliminamos los valores nulos de la columna "Dirección_Normalizada"
df_lesiones_hechos.dropna(subset='Dirección_Normalizada', inplace=True)

In [98]:
#Procederemos a normalizar las direcciones
df_lesiones_hechos['Calle']=df_lesiones_hechos['Calle'].apply(transformar_direccion)
df_lesiones_hechos['Cruce']=df_lesiones_hechos['Cruce'].apply(transformar_direccion)

In [99]:
# Procederemos a reemplazar la dirección por nuestras columnas ya normalizadas
df_lesiones_hechos['Dirección_Normalizada'] = df_lesiones_hechos.apply(
    lambda columna: (
        columna["Calle"] + " Y " + columna["Cruce"]
    ) if (
        isinstance(columna["Cruce"], str) and isinstance(columna["Calle"], str)
    ) else (
        columna["Calle"] if isinstance(columna["Calle"], str)
        else (
            columna["Cruce"] if isinstance(columna["Cruce"], str)
            else columna["Otra_Dirección"]
        )
    ),
    axis=1
)

In [100]:
#Colocamos en mayusculas todas las direcciones
df_lesiones_hechos['Dirección_Normalizada']=df_lesiones_hechos['Dirección_Normalizada'].apply(lambda x: x.upper() if isinstance(x,str) else x)
     

In [101]:
valores_nulos_df(df_lesiones_hechos)

nombre                                       tipo_datos  \
0                      Id                                  [<class 'str'>]   
1       Cantidad_Víctimas                                  [<class 'int'>]   
2                    Anio                                  [<class 'int'>]   
3                     Mes                                  [<class 'int'>]   
4                     Día                                  [<class 'int'>]   
5                   Fecha                    [<class 'datetime.datetime'>]   
6                    Hora                        [<class 'datetime.time'>]   
7           Parte_Horaria                                [<class 'float'>]   
8   Dirección_Normalizada                                  [<class 'str'>]   
9                  Comuna  [<class 'int'>, <class 'str'>, <class 'float'>]   
10             Tipo_Calle                                  [<class 'str'>]   
11         Otra_Dirección                                  [<class 'str'>]   
12                  Calle                 [<class 'float'>, <class 'str'>]   
13                  Cruce                 [<class 'float'>, <class 'str'>]   
14              XY (CABA)                 [<class 'str'>, <class 'float'>]   
15                  Pos X  [<class 'str'>, <class 'float'>, <class 'int'>]   
16                  Pos Y  [<class 'str'>, <class 'float'>, <class 'int'>]   
17                Víctima                                  [<class 'str'>]   
18                Acusado                                  [<class 'str'>]   
19          Participantes                                  [<class 'str'>]   
20                   Moto  [<class 'str'>, <class 'int'>, <class 'float'>]   
21                   Auto  [<class 'str'>, <class 'int'>, <class 'float'>]   
22     Transporte_Público  [<class 'str'>, <class 'int'>, <class 'float'>]   
23                 Camión  [<class 'str'>, <class 'int'>, <class 'float'>]   
24               Ciclista  [<class 'str'>, <class 'float'>, <class 'int'>]   
25               Gravedad                                  [<class 'str'>]   

    nulos_%  nulos  
0      0.00      0  
1      0.00      0  
2      0.00      0  
3      0.00      0  
4      0.00      0  
5      0.00      0  
6      0.00      0  
7      0.00      0  
8      0.00      0  
9      0.67    158  
10     0.00      0  
11     0.00      0  
12    45.78  10865  
13    60.36  14325  
14     0.05     13  
15     0.88    209  
16     0.88    209  
17     0.00      0  
18     0.00      0  
19     0.00      0  
20     0.21     51  
21     0.21     51  
22     0.21     51  
23     0.21     51  
24     0.21     51  
25     0.00      0

In [102]:
df_lesiones_hechos['Comuna'].apply(type).value_counts()

Comuna
<class 'int'>      22328
<class 'str'>       1246
<class 'float'>      158
Name: count, dtype: int64

In [103]:
df_lesiones_hechos

Id  Cantidad_Víctimas  Anio  Mes  Día                Fecha  \
0      2019-0000179                  1  2019    1    1  2019-01-01 00:00:00   
1      2019-0000053                  1  2019    1    1  2019-01-01 00:00:00   
2      2019-0000063                  1  2019    1    1  2019-01-01 00:00:00   
3      2019-0000079                  1  2019    1    1  2019-01-01 00:00:00   
4      2019-0000082                  4  2019    1    1  2019-01-01 00:00:00   
...             ...                ...   ...  ...  ...                  ...   
23780  2021-0652849                  1  2021   12   31  2021-12-31 00:00:00   
23781  2021-0652865                  2  2021   12   31  2021-12-31 00:00:00   
23782  2021-0652907                  1  2021   12   31  2021-12-31 00:00:00   
23783  2021-0652921                  1  2021   12   31  2021-12-31 00:00:00   
23784  2020-0244615                  1  2020    5   17  2020-05-17 00:00:00   

           Hora  Parte_Horaria  \
0      09:00:00            9.0   
1      01:55:00            1.0   
2      02:00:00            2.0   
3      02:30:00            2.0   
4      04:30:00            4.0   
...         ...            ...   
23780  19:30:00           19.0   
23781  19:40:00           19.0   
23782  20:00:00           20.0   
23783  22:00:00           22.0   
23784  21:00:00           21.0   

                                   Dirección_Normalizada Comuna  ...  \
0      OBLIGADO RAFAEL, AV.COSTANERA 3300, BARRIO: PA...     14  ...   
1      AUTOPISTA PRESIDENTE HÉCTOR J. CÁMPORA Y ROCA,...      8  ...   
2      BARROS PAZOS, JOSE Y LARRAYA 0, BARRIO: VILLA ...      8  ...   
3      TORRES Y TENORIO, PRES. Y RIESTRA AV. 0, BARRI...      7  ...   
4      CORRIENTES AV. Y URIBURU JOSE E., PRES. 0, BAR...      3  ...   
...                                                  ...    ...  ...   
23780                AV. JUAN BAUTISTA ALBERDI Y GUAMINI      9  ...   
23781                          AV. JUAN BAUTISTA ALBERDI      9  ...   
23782          BARRIO PADRE CARLOS MUGICA (VILLA 31 BIS)      1  ...   
23783                            LINIERS VIRREY Y MORENO      5  ...   
23784                                                 SD     SD  ...   

                  Pos Y   Víctima             Acusado  \
0            -34.559658  CICLISTA                  SD   
1            -34.669125      AUTO                  SD   
2            -34.677556        SD                  SD   
3            -34.647349    PEATON                  SD   
4            -34.604579      AUTO                  SD   
...                 ...       ...                 ...   
23780  -34.659713573880        SD                  SD   
23781  -34.641753304864        SD                  SD   
23782        -34.583083        SD                  SD   
23783  -34.614288229345      MOTO  TRANSPORTE PUBLICO   
23784       -3472890716      MOTO                AUTO   

                 Participantes Moto Auto Transporte_Público Camión Ciclista  \
0                  CICLISTA-SD   SD   SD                 SD     SD        x   
1                      AUTO-SD   SD    x                 SD     SD       SD   
2                        SD-SD   SD   SD                 SD     SD       SD   
3                    PEATON-SD    x   SD                 SD     SD       SD   
4                      AUTO-SD   SD   SD                  x     SD       SD   
...                        ...  ...  ...                ...    ...      ...   
23780                    SD-SD   SD   SD                 SD     SD       SD   
23781                    SD-SD   SD   SD                 SD     SD       SD   
23782                    SD-SD   SD   SD                 SD     SD       SD   
23783  MOTO-TRANSPORTE PUBLICO    x    0                  x      0        0   
23784                MOTO-AUTO    x    x                  0      0        0   

      Gravedad  
0           SD  
1           SD  
2           SD  
3           SD  
4           SD  
...        ...  
23780       SD  
23781       SD  
23782  

In [104]:
# Convierte la columna 'Comuna' a valores numéricos
df_lesiones_hechos['Comuna']=pd.to_numeric(df_lesiones_hechos['Comuna'], errors='coerce', downcast='integer')

#Eliminamos los valores nulos de la columna "Comuna"
df_lesiones_hechos.dropna(subset='Comuna', inplace=True)

In [105]:
valores_nulos_df(df_lesiones_hechos)

nombre                        tipo_datos  nulos_%  nulos
0                      Id                   [<class 'str'>]     0.00      0
1       Cantidad_Víctimas                   [<class 'int'>]     0.00      0
2                    Anio                   [<class 'int'>]     0.00      0
3                     Mes                   [<class 'int'>]     0.00      0
4                     Día                   [<class 'int'>]     0.00      0
5                   Fecha     [<class 'datetime.datetime'>]     0.00      0
6                    Hora         [<class 'datetime.time'>]     0.00      0
7           Parte_Horaria                 [<class 'float'>]     0.00      0
8   Dirección_Normalizada                   [<class 'str'>]     0.00      0
9                  Comuna                 [<class 'float'>]     0.00      0
10             Tipo_Calle                   [<class 'str'>]     0.00      0
11         Otra_Dirección                   [<class 'str'>]     0.00      0
12                  Calle  [<class 'float'>, <class 'str'>]    43.10   9624
13                  Cruce  [<class 'float'>, <class 'str'>]    58.41  13041
14              XY (CABA)                   [<class 'str'>]     0.00      0
15                  Pos X                   [<class 'str'>]     0.00      0
16                  Pos Y                   [<class 'str'>]     0.00      0
17                Víctima                   [<class 'str'>]     0.00      0
18                Acusado                   [<class 'str'>]     0.00      0
19          Participantes                   [<class 'str'>]     0.00      0
20                   Moto    [<class 'str'>, <class 'int'>]     0.00      0
21                   Auto    [<class 'str'>, <class 'int'>]     0.00      0
22     Transporte_Público    [<class 'str'>, <class 'int'>]     0.00      0
23                 Camión    [<class 'str'>, <class 'int'>]     0.00      0
24               Ciclista    [<class 'str'>, <class 'int'>]     0.00      0
25               Gravedad                   [<class 'str'>]     0.00      0

In [106]:
#Reemplazamos las etiquetas de participacion
df_lesiones_hechos[['Moto','Camión','Auto','Transporte_Público','Ciclista']]=df_lesiones_hechos[['Moto','Camión','Auto','Transporte_Público','Ciclista']].applymap(reemplazar_participacion)

In [107]:
#Se procede a eliminar la columna "Altura"
df_lesiones_hechos.drop(['Calle','Cruce'], axis=1, inplace=True)

In [108]:
valores_nulos_df(df_lesiones_hechos)

nombre                     tipo_datos  nulos_%  nulos
0                      Id                [<class 'str'>]      0.0      0
1       Cantidad_Víctimas                [<class 'int'>]      0.0      0
2                    Anio                [<class 'int'>]      0.0      0
3                     Mes                [<class 'int'>]      0.0      0
4                     Día                [<class 'int'>]      0.0      0
5                   Fecha  [<class 'datetime.datetime'>]      0.0      0
6                    Hora      [<class 'datetime.time'>]      0.0      0
7           Parte_Horaria              [<class 'float'>]      0.0      0
8   Dirección_Normalizada                [<class 'str'>]      0.0      0
9                  Comuna              [<class 'float'>]      0.0      0
10             Tipo_Calle                [<class 'str'>]      0.0      0
11         Otra_Dirección                [<class 'str'>]      0.0      0
12              XY (CABA)                [<class 'str'>]      0.0      0
13                  Pos X                [<class 'str'>]      0.0      0
14                  Pos Y                [<class 'str'>]      0.0      0
15                Víctima                [<class 'str'>]      0.0      0
16                Acusado                [<class 'str'>]      0.0      0
17          Participantes                [<class 'str'>]      0.0      0
18                   Moto                [<class 'int'>]      0.0      0
19                   Auto                [<class 'int'>]      0.0      0
20     Transporte_Público                [<class 'int'>]      0.0      0
21                 Camión                [<class 'int'>]      0.0      0
22               Ciclista                [<class 'int'>]      0.0      0
23               Gravedad                [<class 'str'>]      0.0      0

In [109]:
df_lesiones_hechos.head()

Id  Cantidad_Víctimas  Anio  Mes  Día                Fecha  \
0  2019-0000179                  1  2019    1    1  2019-01-01 00:00:00   
1  2019-0000053                  1  2019    1    1  2019-01-01 00:00:00   
2  2019-0000063                  1  2019    1    1  2019-01-01 00:00:00   
3  2019-0000079                  1  2019    1    1  2019-01-01 00:00:00   
4  2019-0000082                  4  2019    1    1  2019-01-01 00:00:00   

       Hora  Parte_Horaria                              Dirección_Normalizada  \
0  09:00:00            9.0  OBLIGADO RAFAEL, AV.COSTANERA 3300, BARRIO: PA...   
1  01:55:00            1.0  AUTOPISTA PRESIDENTE HÉCTOR J. CÁMPORA Y ROCA,...   
2  02:00:00            2.0  BARROS PAZOS, JOSE Y LARRAYA 0, BARRIO: VILLA ...   
3  02:30:00            2.0  TORRES Y TENORIO, PRES. Y RIESTRA AV. 0, BARRI...   
4  04:30:00            4.0  CORRIENTES AV. Y URIBURU JOSE E., PRES. 0, BAR...   

   Comuna  ...       Pos Y   Víctima Acusado Participantes Moto Auto  \
0    14.0  ...  -34.559658  CICLISTA      SD   CICLISTA-SD    0    0   
1     8.0  ...  -34.669125      AUTO      SD       AUTO-SD    0    1   
2     8.0  ...  -34.677556        SD      SD         SD-SD    0    0   
3     7.0  ...  -34.647349    PEATON      SD     PEATON-SD    1    0   
4     3.0  ...  -34.604579      AUTO      SD       AUTO-SD    0    0   

  Transporte_Público Camión  Ciclista  Gravedad  
0                  0      0         1        SD  
1                  0      0         0        SD  
2                  0      0         0        SD  
3                  0      0         0        SD  
4                  1      0         0        SD  

[5 rows x 24 columns]

In [110]:
#Revisamos los valores unicos de la columna "Víctima"
df_lesiones_hechos['Víctima'].unique()

array(['CICLISTA', 'AUTO', 'SD', 'PEATON', 'MOTO', 'TRANSPORTE PUBLICO',
       'CAMIONETA', 'MOVIL', 'OTRO', 'CAMION', 'UTILITARIO', 'TAXI',
       'MIXTO', 'MONOPATIN'], dtype=object)

In [111]:
# Reemplazamos el valor 'GRAL PAZ' por 'AVENIDA' en la columna 'TIPO_DE_CALLE'
df_lesiones_hechos['Tipo_Calle'].replace('GRAL PAZ', 'AVENIDA', inplace=True)

In [112]:
# Imputa valor mas frecuente en la columna "Tipo_Calle"
imputa_valor_frecuente(df_lesiones_hechos, 'Tipo_Calle')

El valor más frecuente en la columna "Tipo_Calle" es: AVENIDA


In [113]:
# Aplicamos la función estado_gravedad a la columna 'Victima'
df_lesiones_hechos['Gravedad'] = df_lesiones_hechos['Víctima'].apply(estado_gravedad)

In [114]:
# Aplicamos la función sentencia a la columna 'Gravedad'
df_lesiones_hechos['Sentencia'] = df_lesiones_hechos['Gravedad'].apply(sentencia)

In [115]:
# Filtramos las filas donde 'Pos X' es igual a 'SD'
filas_a_eliminar = df_lesiones_hechos[df_lesiones_hechos['Pos X'] == 'SD'].index

# Eliminamos las filas con el filtro aplicado
df_lesiones_hechos = df_lesiones_hechos.drop(filas_a_eliminar)

# Reajustamos los índices si es necesario
df_lesiones_hechos = df_lesiones_hechos.reset_index(drop=True)

In [116]:
#Convertirmos la columnas de "Pos X" a float
df_lesiones_hechos['Pos X'] = df_lesiones_hechos['Pos X'].astype(float)

In [117]:
#Convertirmos la columnas de "Pos Y" a float
df_lesiones_hechos['Pos Y'] = df_lesiones_hechos['Pos Y'].astype(float)

In [118]:
df_lesiones_hechos

Id  Cantidad_Víctimas  Anio  Mes  Día                Fecha  \
0      2019-0000179                  1  2019    1    1  2019-01-01 00:00:00   
1      2019-0000053                  1  2019    1    1  2019-01-01 00:00:00   
2      2019-0000063                  1  2019    1    1  2019-01-01 00:00:00   
3      2019-0000079                  1  2019    1    1  2019-01-01 00:00:00   
4      2019-0000082                  4  2019    1    1  2019-01-01 00:00:00   
...             ...                ...   ...  ...  ...                  ...   
22233  2021-0652812                  1  2021   12   31  2021-12-31 00:00:00   
22234  2021-0652849                  1  2021   12   31  2021-12-31 00:00:00   
22235  2021-0652865                  2  2021   12   31  2021-12-31 00:00:00   
22236  2021-0652907                  1  2021   12   31  2021-12-31 00:00:00   
22237  2021-0652921                  1  2021   12   31  2021-12-31 00:00:00   

           Hora  Parte_Horaria  \
0      09:00:00            9.0   
1      01:55:00            1.0   
2      02:00:00            2.0   
3      02:30:00            2.0   
4      04:30:00            4.0   
...         ...            ...   
22233  18:05:00           18.0   
22234  19:30:00           19.0   
22235  19:40:00           19.0   
22236  20:00:00           20.0   
22237  22:00:00           22.0   

                                   Dirección_Normalizada  Comuna  ...  \
0      OBLIGADO RAFAEL, AV.COSTANERA 3300, BARRIO: PA...    14.0  ...   
1      AUTOPISTA PRESIDENTE HÉCTOR J. CÁMPORA Y ROCA,...     8.0  ...   
2      BARROS PAZOS, JOSE Y LARRAYA 0, BARRIO: VILLA ...     8.0  ...   
3      TORRES Y TENORIO, PRES. Y RIESTRA AV. 0, BARRI...     7.0  ...   
4      CORRIENTES AV. Y URIBURU JOSE E., PRES. 0, BAR...     3.0  ...   
...                                                  ...     ...  ...   
22233                                               VIEL     6.0  ...   
22234                AV. JUAN BAUTISTA ALBERDI Y GUAMINI     9.0  ...   
22235                          AV. JUAN BAUTISTA ALBERDI     9.0  ...   
22236          BARRIO PADRE CARLOS MUGICA (VILLA 31 BIS)     1.0  ...   
22237                            LINIERS VIRREY Y MORENO     5.0  ...   

        Víctima             Acusado            Participantes  Moto  Auto  \
0      CICLISTA                  SD              CICLISTA-SD     0     0   
1          AUTO                  SD                  AUTO-SD     0     1   
2            SD                  SD                    SD-SD     0     0   
3        PEATON                  SD                PEATON-SD     1     0   
4          AUTO                  SD                  AUTO-SD     0     0   
...         ...                 ...                      ...   ...   ...   
22233        SD                  SD                    SD-SD     0     0   
22234        SD                  SD                    SD-SD     0     0   
22235        SD                  SD                    SD-SD     0     0   
22236        SD                  SD                    SD-SD     0     0   
22237      MOTO  TRANSPORTE PUBLICO  MOTO-TRANSPORTE PUBLICO     1     0   

      Transporte_Público Camión Ciclista            Gravedad     Sentencia  
0                      0      0        1     LESIONES GRAVES  DELITO GRAVE  
1                      0      0        0  LESIONES MODERADAS   DELITO LEVE  
2                      0      0        0      LESIONES LEVES         FALTA  
3                      0      0        0     LESIONES GRAVES  DELITO GRAVE  
4                      1      0        0  LESIONES MODERADAS   DELITO LEVE  
...                  ...    ...      ...                 ...           ...  
22233                  0      0        0      LESIONES LEVES         FALTA  
22234                  0      0        0      LESIONES LEVES         FALTA  
22235                  0      0        0      LESIONES LEVES         FALTA  
22236                  0      0        0      LESIONES LEVES         FALTA  
22237                 

##### *df_lesiones_victimas*

In [119]:
#Visualizaremos las columnas de nuestro DataFrame "df_lesiones_victimas"
df_lesiones_victimas.columns

Index(['ID hecho', 'AAA', 'MM', 'DD', 'FECHA ', 'VEHICULO_VICTIMA', 'SEXO',
       'EDAD_VICTIMA', 'GRAVEDAD'],
      dtype='object')

In [120]:
# Se coloca la primera letra en mayúscula y se reemplazan guiones por espacios
df_lesiones_victimas.columns = [x.capitalize() for x in df_lesiones_victimas.columns]

# Se renombran algunas columnas
df_lesiones_victimas = df_lesiones_victimas.rename(columns={'Id hecho':'Id',
                                                      'Aaa':'Anio',
                                                      'Mm':'Mes',
                                                      'Dd':'Día',
                                                      'Fecha ': 'Fecha',
                                                      'Vehiculo_victima':'Vehículo_Víctima',
                                                      'Edad_victima':'Edad'
                                                      })
#Visualizamos los nombres nuevos de nuestras columnas 
df_lesiones_victimas.columns

Index(['Id', 'Anio', 'Mes', 'Día', 'Fecha', 'Vehículo_Víctima', 'Sexo', 'Edad',
       'Gravedad'],
      dtype='object')

In [121]:
valores_nulos_df(df_lesiones_victimas)

nombre                                         tipo_datos  \
0                Id                                    [<class 'str'>]   
1              Anio                                    [<class 'int'>]   
2               Mes                                    [<class 'int'>]   
3               Día                                    [<class 'int'>]   
4             Fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
5  Vehículo_Víctima                                    [<class 'str'>]   
6              Sexo                                    [<class 'str'>]   
7              Edad                     [<class 'int'>, <class 'str'>]   
8          Gravedad                                    [<class 'str'>]   

   nulos_%  nulos  
0      0.0      0  
1      0.0      0  
2      0.0      0  
3      0.0      0  
4      0.0      0  
5      0.0      0  
6      0.0      0  
7      0.0      0  
8      0.0      0

In [122]:
#También pasamos a verificar si existen Ids duplicados
verifica_duplicados(df_lesiones_victimas,'Id')

Id  Anio  Mes  Día      Fecha Vehículo_Víctima   Sexo  \
16188   HC-2020-0499647  2020    8   30 2020-08-30             AUTO  varon   
16187   HC-2020-0499647  2020    8   30 2020-08-30             AUTO  mujer   
16186   HC-2020-0499647  2020    8   30 2020-08-30             AUTO  varon   
22822   HC-2021-0147160  2021    3   31 2021-03-31               SD  Varon   
22821   HC-2021-0147160  2021    3   31 2021-03-31               SD  Varon   
...                 ...   ...  ...  ...        ...              ...    ...   
26889   LC-2021-0652316  2021   12   31 2021-12-31             AUTO  Mujer   
26479   LC-2021-0652865  2021   12   31 2021-12-31               SD  Varon   
26478   LC-2021-0652865  2021   12   31 2021-12-31               SD  Varon   
18654  LC-2021-34095003  2021    8   17 2021-08-17             AUTO  Varon   
18653  LC-2021-34095003  2021    8   17 2021-08-17             AUTO  Varon   

      Edad Gravedad  
16188   60       SD  
16187   44       SD  
16186   19       SD  
22822   45       SD  
22821   64       SD  
...    ...      ...  
26889   82       SD  
26479   52       SD  
26478   28       SD  
18654   34       SD  
18653   33       SD  

[6572 rows x 9 columns]

In [123]:
# Modificamos la composición de la columna Id para asemejarla a la de homicidios
df_lesiones_victimas['Id'] = df_lesiones_victimas['Id'].str.replace('LC-', '').str.strip()

In [124]:
# Visualizamos la cantidad de valores por tipo de dato en la columna 'Edad'
df_lesiones_victimas['Edad'].apply(type).value_counts()

Edad
<class 'int'>    18838
<class 'str'>     8767
Name: count, dtype: int64

In [125]:
"""
Para imputar los valores faltantes en la columna 'Edad', se planea utilizar el promedio de las edades de las víctimas, 
considerando el género ('Sexo'). Dado que la variable 'Sexo' también presenta faltantes, se procederá a completar estos valores 
utilizando el valor más frecuente entre las víctimas. Luego, con ambas columnas actualizadas, se calculará el promedio de las edades 
por género y se utilizará este promedio para imputar los valores faltantes en la columna 'Edad', asegurando así una imputación más 
precisa y contextualizada. Este enfoque tiene como objetivo gestionar de manera integral los datos faltantes, considerando tanto la 
información de género como la de edad, para obtener resultados más significativos y representativos.

"""
# Filtramos las filas donde la columna 'Edad' contiene valores de tipo cadena (str)
df_lesiones_victimas[df_lesiones_victimas['Edad'].apply(lambda x: isinstance(x, str))]

Id  Anio  Mes  Día      Fecha Vehículo_Víctima   Sexo Edad  \
1      2019-0000063  2019    1    1 2019-01-01               sd     SD   SD   
2      2019-0000079  2019    1    1 2019-01-01               sd  Varon   SD   
10     2019-0000179  2019    1    1 2019-01-01               sd     SD   SD   
14     2019-0000347  2019    1    1 2019-01-01               sd  Varon   SD   
21     2019-0000647  2019    1    1 2019-01-01               sd  Varon   SD   
...             ...   ...  ...  ...        ...              ...    ...  ...   
27578  2021-0000449  2021    1    1 2021-01-01               SD     SD   SD   
27589  2021-0078012  2021    2   21 2021-02-21               SD     SD   SD   
27595  2021-0230174  2021    5   26 2021-05-26               SD     SD   SD   
27596  2021-0305042  2021    6   28 2021-06-28             AUTO     SD   SD   
27597  2021-0305042  2021    6   28 2021-06-28             AUTO     SD   SD   

      Gravedad  
1           SD  
2           SD  
10          SD  
14          SD  
21          SD  
...        ...  
27578       SD  
27589       SD  
27595       SD  
27596       SD  
27597       SD  

[8767 rows x 9 columns]

In [126]:
#Cambiamos a integer los datos de la columna EDAD
df_lesiones_victimas['Edad']=pd.to_numeric(df_lesiones_victimas['Edad'], errors='coerce')

In [127]:
#Eliminamos los valores nulos
df_lesiones_victimas.dropna(subset=['Edad'], inplace=True)

In [128]:
df_lesiones_victimas['Sexo'].unique()

array(['Varon', 'Mujer', 'SD', 'varon', 'mujer', 'MUJER', 'Mujer '],
      dtype=object)

In [129]:
# Reemplazamos valores específicos en la columna 'Sexo'
df_lesiones_victimas['Sexo'] = df_lesiones_victimas['Sexo'].replace(to_replace=['Varon', 'varon'], value='MASCULINO')
df_lesiones_victimas['Sexo'] = df_lesiones_victimas['Sexo'].replace(to_replace=['Mujer','mujer','MUJER','Mujer '], value='FEMENINO')

In [130]:
# Imputa valor mas frecuente en la columna "Sexo"
imputa_valor_frecuente(df_lesiones_victimas, 'Sexo')

El valor más frecuente en la columna "Sexo" es: MASCULINO


In [131]:
#Imputamos el valor de la edad teniendo el "Sexo"
imputa_edad_media_segun_sexo(df_lesiones_victimas)

La edad promedio de Femenino es 40 y de Masculino es 37


In [132]:
# Creamos la columna "Rango_Etario" utilizando la función asignar_rango_etario
df_lesiones_victimas['Rango_Etario'] = df_lesiones_victimas['Edad'].apply(lambda x: rango_etario(x))

In [133]:
# Contar la cantidad de "SD" en la columna "Sexo"
cantidad_sd_en_sexo = len(df_lesiones_victimas[df_lesiones_victimas['Sexo'] == 'SD'])
print(f"La cantidad de 'SD' en la columna 'Rol' es de {cantidad_sd_en_sexo}")

# Contar la cantidad de "SD" en la columna "Edad"
cantidad_sd_en_edad = len(df_lesiones_victimas[df_lesiones_victimas['Edad'] == 'SD'])
print(f"La cantidad de 'SD' en la columna 'Víctima' es de {cantidad_sd_en_edad}")

# Contar la cantidad de "SD" en la columna "Vehículo_Víctima"
cantidad_sd_en_vehiculo = len(df_lesiones_victimas[df_lesiones_victimas['Vehículo_Víctima'] == 'sd'])
print(f"La cantidad de 'SD' en la columna 'Vehículo_Víctima' es de {cantidad_sd_en_vehiculo}")

# Contar la cantidad de "SD" en la columna "Edad"
cantidad_sd_en_gravedad = len(df_lesiones_victimas[df_lesiones_victimas['Gravedad'] == 'SD'])
print(f"La cantidad de 'SD' en la columna 'Gravedad' es de {cantidad_sd_en_gravedad}")



La cantidad de 'SD' en la columna 'Rol' es de 0
La cantidad de 'SD' en la columna 'Víctima' es de 0
La cantidad de 'SD' en la columna 'Vehículo_Víctima' es de 9541
La cantidad de 'SD' en la columna 'Gravedad' es de 17338


In [134]:
# Imputa valor mas frecuente en la columna "Vehículo_Víctima"
imputa_valor_frecuente(df_lesiones_victimas, 'Vehículo_Víctima')

El valor más frecuente en la columna "Vehículo_Víctima" es: MOTO


In [135]:
# Reemplazamos valores específicos en la columna 'Gravedad'
df_lesiones_victimas.loc[df_lesiones_victimas['Gravedad'] == 'GRAVE', 'Gravedad'] = 'LESIONES GRAVES'
df_lesiones_victimas.loc[df_lesiones_victimas['Gravedad'] == 'grave', 'Gravedad'] = 'LESIONES GRAVES'
df_lesiones_victimas.loc[df_lesiones_victimas['Gravedad'] == 'SD', 'Gravedad'] = 'SD'

In [136]:
# Aplicamos la función estado_gravedad a la columna 'Vehículo_Víctima'
df_lesiones_victimas['Gravedad'] = df_lesiones_victimas['Vehículo_Víctima'].apply(estado_gravedad)

In [137]:
# Aplicamos la función sentencia a la columna 'Gravedad'
df_lesiones_victimas['Sentencia'] = df_lesiones_victimas['Gravedad'].apply(sentencia)

In [138]:
df_lesiones_victimas

Id  Anio  Mes  Día      Fecha    Vehículo_Víctima       Sexo  \
0      2019-0000053  2019    1    1 2019-01-01                MOTO  MASCULINO   
3      2019-0000082  2019    1    1 2019-01-01                MOTO  MASCULINO   
4      2019-0000082  2019    1    1 2019-01-01                MOTO   FEMENINO   
5      2019-0000082  2019    1    1 2019-01-01                MOTO  MASCULINO   
6      2019-0000082  2019    1    1 2019-01-01                MOTO   FEMENINO   
...             ...   ...  ...  ...        ...                 ...        ...   
27600  2021-0451911  2021    9   11 2021-09-11  TRANSPORTE PUBLICO  MASCULINO   
27601  2021-0530228  2021   10   25 2021-10-25  TRANSPORTE PUBLICO   FEMENINO   
27602  2021-0530228  2021   10   25 2021-10-25  TRANSPORTE PUBLICO   FEMENINO   
27603  2021-0201378  2021    5    2 2021-05-02                MOTO  MASCULINO   
27604  2021-0229350  2021    5   19 2021-05-19                MOTO  MASCULINO   

       Edad         Gravedad         Rango_Etario     Sentencia  
0        57  LESIONES GRAVES         ADULTO MAYOR  DELITO GRAVE  
3        45  LESIONES GRAVES        ADULTO MADURO  DELITO GRAVE  
4        45  LESIONES GRAVES        ADULTO MADURO  DELITO GRAVE  
5        27  LESIONES GRAVES         ADULTO JOVEN  DELITO GRAVE  
6        32  LESIONES GRAVES  ADULTO MEDIANA EDAD  DELITO GRAVE  
...     ...              ...                  ...           ...  
27600    87   LESIONES LEVES         TERCERA EDAD         FALTA  
27601    60   LESIONES LEVES         TERCERA EDAD         FALTA  
27602    32   LESIONES LEVES  ADULTO MEDIANA EDAD         FALTA  
27603    32  LESIONES GRAVES  ADULTO MEDIANA EDAD  DELITO GRAVE  
27604    41  LESIONES GRAVES        ADULTO MADURO  DELITO GRAVE  

[23134 rows x 11 columns]

##### *unión_DataFrames*

In [139]:
# Concatenamos los DataFrames de víctimas de homicidios y lesiones para formar 'homicidios'
homicios_final = df_homicidios_victimas.merge(df_homicidios_hechos, on='Id', how='left')

In [140]:
# Eliminar la columnas que son poco relevantes o redundantes
homicios_final.drop(['Fecha_y', 'Anio_y', 'Mes_y', 'Día_y', 'Gravedad_y', 'Sentencia_y', 'XY (CABA)'], axis=1, inplace=True)

In [141]:
# Se renombran algunas columnas
homicios_final = homicios_final.rename(columns={'Fecha_x':'Fecha', 
                                                'Anio_x':'Anio',
                                                'Mes_x':'Mes',
                                                'Día_x':'Día',
                                                'Gravedad_x':'Gravedad',
                                                'Sentencia_x':'Sentencia',
                                                })

In [142]:
homicios_final

Id      Fecha  Anio  Mes  Día        Rol Victima       Sexo  Edad  \
0    2016-0001 2016-01-01  2016    1    1  CONDUCTOR    MOTO  MASCULINO    19   
1    2016-0002 2016-01-02  2016    1    2  CONDUCTOR    AUTO  MASCULINO    70   
2    2016-0003 2016-01-03  2016    1    3  CONDUCTOR    MOTO  MASCULINO    30   
3    2016-0004 2016-01-10  2016    1   10  CONDUCTOR    MOTO  MASCULINO    18   
4    2016-0005 2016-01-21  2016    1   21  CONDUCTOR    MOTO  MASCULINO    29   
..         ...        ...   ...  ...  ...        ...     ...        ...   ...   
712  2021-0092 2021-12-12  2021   12   12     PEATON  PEATON   FEMENINO    50   
713  2021-0093 2021-12-13  2021   12   13   PASAJERO    MOTO   FEMENINO    18   
714  2021-0094 2021-12-20  2021   12   20   PASAJERO    MOTO   FEMENINO    43   
715  2021-0095 2021-12-30  2021   12   30  CONDUCTOR    MOTO  MASCULINO    27   
716  2021-0096 2021-12-15  2021   12   15  CONDUCTOR    AUTO  MASCULINO    60   

    Gravedad  ... Tipo_de_Calle                             Calle  Cruce  \
0      FATAL  ...       AVENIDA                  AV. PIEDRA BUENA     SI   
1      FATAL  ...       AVENIDA                   AV. GENERAL PAZ     SI   
2      FATAL  ...       AVENIDA                    AV. ENTRE RIOS     NO   
3      FATAL  ...       AVENIDA                    AV. LARRAZABAL     SI   
4      FATAL  ...       AVENIDA                      AV. SAN JUAN     SI   
..       ...  ...           ...                               ...    ...   
712    FATAL  ...       AVENIDA                     AV. RIVADAVIA     SI   
713    FATAL  ...       AVENIDA                       AV. RIESTRA     SI   
714    FATAL  ...     AUTOPISTA  TENIENTE GENERAL LUIS DELLEPIANE     SI   
715    FATAL  ...       AVENIDA                         AV. GAONA     SI   
716    FATAL  ...       AVENIDA                     AV. EVA PERON     NO   

                     Dirección_Normalizada Comuna         Pos X         Pos Y  \
0                    AV. PIEDRA BUENA Y SI      8  -58.47533969  -34.68757022   
1                     AV. GENERAL PAZ Y SI      9  -58.50877521  -34.66977709   
2                      AV. ENTRE RIOS Y NO      1  -58.39040293  -34.63189362   
3                      AV. LARRAZABAL Y SI      8  -58.46503904  -34.68092974   
4                        AV. SAN JUAN Y SI      1  -58.38718297  -34.62246630   
..                                     ...    ...           ...           ...   
712                     AV. RIVADAVIA Y SI      3  -58.40596860  -34.61011987   
713                       AV. RIESTRA Y SI      7  -58.43353773  -34.64561636   
714  TENIENTE GENERAL LUIS DELLEPIANE Y SI      9  -58.46739825  -34.65117757   
715                         AV. GAONA Y SI     11  -58.47293407  -34.61984745   
716                     AV. EVA PERON Y NO      9  -58.47066794  -34.65021673   

      Participantes Víctima    Acusado  
0         MOTO-AUTO    MOTO       AUTO  
1    AUTO-PASAJEROS    AUTO  PASAJEROS  
2         MOTO-AUTO    MOTO       AUTO  
3           MOTO-SD    MOTO         SD  
4    MOTO-PASAJEROS    MOTO  PASAJEROS  
..              ...     ...        ...  
712     PEATON-AUTO  PEATON       AUTO  
713       MOTO-AUTO    MOTO       AUTO  
714       MOTO-AUTO    MOTO       AUTO  
715     MOTO-CARGAS    MOTO     CARGAS  
716     AUTO-CARGAS    AUTO     CARGAS  

[717 rows x 26 columns]

In [143]:
# Concatenamos los DataFrames de víctimas de homicidios y lesiones para formar 'lesiones'
lesiones_final = df_lesiones_victimas.merge(df_lesiones_hechos, on='Id', how='left')

In [144]:
# Eliminar valores nulos de la columna "Víctima"
lesiones_final.dropna(subset=['Víctima'], inplace=True)

In [145]:
# Eliminar la columnas que son poco relevantes o redundantes
lesiones_final.drop(['Anio_y', 'Mes_y', 'Día_y', 'Fecha_y','Otra_Dirección', 'XY (CABA)','Gravedad_y', 'Sentencia_y'], axis=1, inplace=True)


In [146]:
# Se renombran algunas columnas
lesiones_final = lesiones_final.rename(columns={'Fecha_x':'Fecha', 
                                                'Anio_x':'Anio',
                                                'Mes_x':'Mes',
                                                'Día_x':'Día',
                                                'Gravedad_x':'Gravedad',
                                                'Sentencia_x':'Sentencia',
                                                })

In [147]:
lesiones_final

Id  Anio  Mes  Día      Fecha    Vehículo_Víctima       Sexo  \
0      2019-0000053  2019    1    1 2019-01-01                MOTO  MASCULINO   
1      2019-0000082  2019    1    1 2019-01-01                MOTO  MASCULINO   
2      2019-0000082  2019    1    1 2019-01-01                MOTO   FEMENINO   
3      2019-0000082  2019    1    1 2019-01-01                MOTO  MASCULINO   
4      2019-0000082  2019    1    1 2019-01-01                MOTO   FEMENINO   
...             ...   ...  ...  ...        ...                 ...        ...   
23124  2021-0314490  2021    7    4 2021-07-04                AUTO   FEMENINO   
23127  2021-0305042  2021    6   28 2021-06-28                AUTO   FEMENINO   
23129  2021-0451911  2021    9   11 2021-09-11  TRANSPORTE PUBLICO  MASCULINO   
23130  2021-0530228  2021   10   25 2021-10-25  TRANSPORTE PUBLICO   FEMENINO   
23131  2021-0530228  2021   10   25 2021-10-25  TRANSPORTE PUBLICO   FEMENINO   

       Edad            Gravedad         Rango_Etario  ...      Pos X  \
0        57     LESIONES GRAVES         ADULTO MAYOR  ... -58.443510   
1        45     LESIONES GRAVES        ADULTO MADURO  ... -58.398225   
2        45     LESIONES GRAVES        ADULTO MADURO  ... -58.398225   
3        27     LESIONES GRAVES         ADULTO JOVEN  ... -58.398225   
4        32     LESIONES GRAVES  ADULTO MEDIANA EDAD  ... -58.398225   
...     ...                 ...                  ...  ...        ...   
23124    17  LESIONES MODERADAS          ADOLESCENTE  ... -58.516666   
23127    32  LESIONES MODERADAS  ADULTO MEDIANA EDAD  ... -58.437401   
23129    87      LESIONES LEVES         TERCERA EDAD  ... -58.420119   
23130    60      LESIONES LEVES         TERCERA EDAD  ... -58.406897   
23131    32      LESIONES LEVES  ADULTO MEDIANA EDAD  ... -58.406897   

           Pos Y             Víctima             Acusado  \
0     -34.669125                AUTO                  SD   
1     -34.604579                AUTO                  SD   
2     -34.604579                AUTO                  SD   
3     -34.604579                AUTO                  SD   
4     -34.604579                AUTO                  SD   
...          ...                 ...                 ...   
23124 -34.589996                AUTO                  SD   
23127 -34.581710                AUTO               MOVIL   
23129 -34.581370  TRANSPORTE PUBLICO  TRANSPORTE PUBLICO   
23130 -34.581142  TRANSPORTE PUBLICO  TRANSPORTE PUBLICO   
23131 -34.581142  TRANSPORTE PUBLICO  TRANSPORTE PUBLICO   

                               Participantes  Moto Auto  Transporte_Público  \
0                                    AUTO-SD   0.0  1.0                 0.0   
1                                    AUTO-SD   0.0  0.0                 1.0   
2                                    AUTO-SD   0.0  0.0                 1.0   
3                                    AUTO-SD   0.0  0.0                 1.0   
4                                    AUTO-SD   0.0  0.0                 1.0   
...                                      ...   ...  ...                 ...   
23124                                AUTO-SD   0.0  1.0                 0.0   
23127                             AUTO-MOVIL   0.0  1.0                 0.0   
23129  TRANSPORTE PUBLICO-TRANSPORTE PUBLICO   0.0  0.0                 1.0   
23130  TRANSPORTE PUBLICO-TRANSPORTE PUBLICO   0.0  0.0                 1.0   
23131  TRANSPORTE PUBLICO-TRANSPORTE PUBLICO   0.0  0.0                 1.0   

       Camión Ciclista  
0         0.0      0.0  
1         0.0      0.0  
2         0.0      0.0  
3         0.0      0.0  
4         0.0      0.0  
...       ...      ...  
23124     0.0      0.0  
23127     0.0      0.0  
23129     0.0      0.0  
23130     0.0      0.0  
23131     0.0      0.0  

[21667 rows x 27 columns]

### 2.4. Exportación de DataSet Limpia

In [293]:
#Se guarda el dataframe transformado como steam_games_clean
archivo_limpio = r'Dataset_Clean/homicidios_clean.csv'
homicios_final.to_csv(archivo_limpio, index=False, encoding='utf-8')
print(f'Se guardó el archivo {archivo_limpio}')

Se guardó el archivo Dataset_Clean/homicidios_clean.csv


In [294]:
#Se guarda el dataframe transformado como steam_games_clean
archivo_limpio = r'Dataset_Clean/lesiones_clean.csv'
lesiones_final.to_csv(archivo_limpio, index=False, encoding='utf-8')
print(f'Se guardó el archivo {archivo_limpio}')

Se guardó el archivo Dataset_Clean/lesiones_clean.csv


In [295]:
#Se guarda el dataframe transformado como steam_games_clean
archivo_limpio_csv = 'Dataset_Clean/homicidios_clean.csv'
archivo_limpio_parquet = 'Dataset_Clean/homicidios_clean.parquet'
# Leemos el archivo CSV en un DataFrame
df = pd.read_csv(archivo_limpio_csv)
df.to_parquet(archivo_limpio_parquet, engine='pyarrow')
print(f'Se guardó el archivo {archivo_limpio_parquet}')

Se guardó el archivo Dataset_Clean/homicidios_clean.parquet


In [296]:
#Se guarda el dataframe transformado como steam_games_clean
archivo_limpio_csv = 'Dataset_Clean/lesiones_clean.csv'
archivo_limpio_parquet = 'Dataset_Clean/lesiones_clean.parquet'
# Leemos el archivo CSV en un DataFrame
df = pd.read_csv(archivo_limpio_csv)
df.to_parquet(archivo_limpio_parquet, engine='pyarrow')
print(f'Se guardó el archivo {archivo_limpio_parquet}')

Se guardó el archivo Dataset_Clean/lesiones_clean.parquet
